### ISSUE TITLE
[FEATURE] Add support for flag state

### ISSUE THREAD

**Issue by beeme1mr** [open-feature/flagd#102]
### Requirements

The flag configuration contains a state property. This property can be either `ENABLED` or `DISABLED` according to the [schema](https://github.com/open-feature/schemas/blob/main/json/flagd-definitions.json#L45). This value is an enum and may contain additional states in the future.

If the state is `ENABLED`, flagD should behave like it does now. However, if the state is `DISABLED`, flagD should return an error stating that the flag is disabled. The OpenFeature SDK would catch this error and use the fallback value.

**Comment by skyerus** [comment]
https://github.com/open-feature/flagd/pull/127
