### ISSUE TITLE
[BUG] Go install fails due to generated dependencies missing

### ISSUE THREAD

**Issue by AlexsJones** [open-feature/flagd#105]
### Observed behavior

```
 go install github.com/open-feature/flagd@latest
go: finding module for package github.com/open-feature/flagd/schemas/proto/go-server/schema/v1
.gvm/pkgsets/go1.18.3/global/pkg/mod/github.com/open-feature/flagd@v0.0.6/pkg/eval/json_evaluator.go:18:12: pattern flagd-definitions.json: no matching files found
.gvm/pkgsets/go1.18.3/global/pkg/mod/github.com/open-feature/flagd@v0.0.6/pkg/service/grpc_service.go:10:2: module github.com/open-feature/flagd@latest found (v0.0.6), but does not contain package github.com/open-feature/flagd/schemas/proto/go-server/schema/v1
```

### Steps to reproduce

```
go install github.com/open-feature/flagd@latest
```

Using golang >1.18

**Comment by beeme1mr** [comment]
It looks like the `go install` process doesn't support git submodules. In fact, the downloaded flagD folder doesn't contains a .git folder at all. Even manually it's not possible to run `git submodule update --init --recursive`.

It looks like we need to check in our generated code. OTel does this in a [separate repo](https://github.com/open-telemetry/opentelemetry-proto-go) but that may be needless complexity for us right now. We could rely on Buf to generate the dependency on-demand. @james-milligan has already done something similar in the [flagD provider](https://github.com/open-feature/golang-sdk-contrib/blob/1fbf1eb98a150d792ffc1cd1c6164e9cac16e299/providers/flagd/pkg/service/grpc/client.go#L7). If we go the Buf route, we'll need to make sure the json schema is checked into the flagD repo.

**Comment by james-milligan** [comment]
Ive put together an example following on from the [flagD provider example](https://github.com/open-feature/golang-sdk-contrib/blob/1fbf1eb98a150d792ffc1cd1c6164e9cac16e299/providers/flagd/pkg/service/grpc/client.go#L7). It uses a [custom template](https://buf.build/open-feature/templates/flagd-server) and the existing [flagd schema](https://buf.build/open-feature/flagd) to generate both the grpc and grpc-gateway code and access it as though it was a go package! [buf remote generation reference](https://docs.buf.build/tour/use-remote-generation)

One important thing to note regarding this approach is that remote generation is currently in alpha

```go get go.buf.build/open-feature/flagd-server/open-feature/flagd```

**Comment by AlexsJones** [comment]
This looks promising

**Comment by toddbaert** [comment]
Using the buf remote generation makes sense to me. I'd like to avoid committing the .json to the flagd repo though. I think the only reason we need it if we use the remote generation is for validation, right? (correct me if I'm wrong).

Could we perhaps publish the schema in a go module from the schemas repo? We could [embed](https://pkg.go.dev/embed) the schema json in a go module and pull that in as a go dependency, perhaps? 

Then flagd would consume this dependency and have access to the JSON. Would that avoid the need to commit the json file if we're also using the remote generation?

**Comment by beeme1mr** [comment]
> Could we perhaps publish the schema in a go module from the schemas repo? We could [embed](https://pkg.go.dev/embed) the schema json in a go module and pull that in as a go dependency, perhaps?

I think that would work fine.

**Comment by beeme1mr** [comment]
v0.0.8 or above now works with `go install `
