### ISSUE TITLE
Formalize flagD release process

### ISSUE THREAD

**Issue by beeme1mr** [open-feature/flagd#106]
Based on community feedback, the following items need to be configured to 

- [x] PRs require at least two approvers
- [x] Add an owners file
- [ ] #108
- [x] #107
- [x] #109
- [x] #110
- [x] #111
- [x] #112

Additional notes:

- Breaking changes need to be included in the release notes but does **NOT** require a major version bump until v1.0
- PRs that are not ready to be merged must be marked as a draft
- When a PR is ready, the final approver should merge the PR.

**Comment by beeme1mr** [comment]
We could consider enabling [auto merging](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/incorporating-changes-from-a-pull-request/automatically-merging-a-pull-request). FYI, @thomaspoignant @AlexsJones @toddbaert

**Comment by AlexsJones** [comment]
I am okay with this, given we have two reviewers and comment resolution I think this is fine to turn on

**Comment by beeme1mr** [comment]
https://github.com/marketplace/actions/todo-to-issue
