### ISSUE TITLE
Add contributing doc to the repo

### ISSUE THREAD

**Issue by beeme1mr** [open-feature/flagd#108]
## Summary

Add a contributing document to the root of the repo. People interested in contributing for the first time can use this document to understand how they should get started. For a basic example, please refer to the [contributing docs in the js contrib repo](https://github.com/open-feature/js-sdk-contrib/blob/main/CONTRIBUTING.md).

**Comment by skyerus** [comment]
This has already been done: https://github.com/open-feature/flagd/blob/main/CONTRIBUTING.md
