### ISSUE TITLE
[FEATURE] Code sign Apple OS binaries w/ Apple developer key?

### ISSUE THREAD

**Issue by agardnerIT** [open-feature/flagd#1121]
### Requirements

When attempting to run the darwin flagd images on macos, Apple blocks the binaries and we must manually override and allow.

While this is **not a bug**, it may be better the project could sign the binaries using an Apple code signing certificate. An Apple account and paid subscription is necessary, but I wonder if the CNCF have an agreement with Apple?

**Comment by beeme1mr** [comment]
I'm going to close this since it's unlikely we'll get an Apple developer key in the near future. Please use the containerized version of flagd if possible.
