### ISSUE TITLE
[FEATURE] Add `targeting` validation and log warning if targeting is invalid

### ISSUE THREAD

**Issue by toddbaert** [open-feature/flagd#1140]
### Requirements

With https://github.com/open-feature/flagd-schemas/pull/120, we now have JSON schema validation for targeting rules. We can now validate targeting rules for all sources. We should do this, and log a WARNING anytime an flag with invalid targeting is configured.

Tasks:

- [ ] update `schemas` submodule to most recent release
- [ ] add `targeting` and root schema (see [example here](https://github.com/open-feature/flagd-schemas/blob/b812f93c8a611614a83a52f3c8583f7ecd130754/json/flagd_definitions_test.go#L18-L27)) and validate it, logging a warning if it's not valid

**Comment by toddbaert** [comment]
@Olunusib would you like me to assign this to you?

**Comment by Olunusib** [comment]
Yes please, thanks!
