### ISSUE TITLE
[FEATURE] Support any auth scheme in HTTP-sync auth header

### ISSUE THREAD

**Issue by toddbaert** [open-feature/flagd#1150]
### Requirements

Currently, we only support the `Bearer` scheme (see code [here](https://github.com/open-feature/flagd/blob/2adfa573a29692d293b37c52b3daf048fd5850d6/core/pkg/sync/http/http_sync.go#L124)). We should support [any scheme](https://developer.mozilla.org/en-US/docs/Web/HTTP/Authentication#authentication_schemes).

We can do this by simply letting authors specify the entire contents of the Auth header.

Tasks:

- [ ] deprecate [BasicAuth](https://github.com/open-feature/flagd/blob/2adfa573a29692d293b37c52b3daf048fd5850d6/core/pkg/sync/isync.go#L68) option (but continue to support it) so this isn't a breaking change
- [ ] add new AuthHeader option, which defines entire auth header as an alternative to `BasicAuth` and send in HTTP request
- [ ] document new option, and interaction with deprecated `basicAuth` option "dealer's choice" here: 
  - throw an error if both are defined?
  - default to ignore one if the other is defined?
- [ ] tests

**Comment by Olunusib** [comment]
I'd like to pick this up

**Comment by toddbaert** [comment]
@Olunusib it's yours!

I believe this will be at least your 3rd contribution? Would  you like to join the org? I can create a PR to add/invite you. There's no obligation if you join.

With what you've already contributed, you're on track to progress up the [contributor ladder](https://github.com/open-feature/community/blob/main/CONTRIBUTOR_LADDER.md) already.

**Comment by Olunusib** [comment]
Yes, happy to be a member of the org!

**Comment by toddbaert** [comment]
> Yes, happy to be a member of the org!

https://github.com/open-feature/community/pull/328
