### ISSUE TITLE
[BUG] Schema support for Boolean Variant Shorthand

### ISSUE THREAD

**Issue by austindrenski** [open-feature/flagd#1205]
### Observed behavior

_Not really a bug, but also not really a feature 🤷_

> Property 'if' is not allowed 
>
> Array is shorter than 2 

![image](https://github.com/open-feature/flagd/assets/21338699/1ed743bd-c54a-400a-b29d-db672029f061)

![image](https://github.com/open-feature/flagd/assets/21338699/cd09f141-8665-4528-ba7a-a87cbeebf3ae)

### Expected Behavior

- https://flagd.dev/reference/flag-definitions/#boolean-variant-shorthand

### Steps to reproduce

```json
{
  "flags": {
    "some-flag": {
      "state": "ENABLED",
      "variants": {
        "true": true,
        "false": false
      },
      "defaultVariant": "true",
      "targeting": {
        "if": [
          {
            "$ref": "env-production"
          }
        ]
      }
    }
  },
  "$evaluators": {
    "env-production": {
      "===": [
        {
          "var": "env"
        },
        "production"
      ]
    }
  }
}
```

**Comment by beeme1mr** [comment]
We may need to special case `$ref`. FYI @toddbaert

**Comment by toddbaert** [comment]
@beeme1mr 

I don't think this has anything to do with ref (or I'm confused).

If you replace @austindrenski 's example without a ref, it still doesn't validate:

The problem is that if works just fine in shorthand with not just 2, but also 1 arg. We only support 2-3, and can add support for just 1.

**Comment by toddbaert** [comment]
I'll fix this in the next couple days, should be fairly simple.

**Comment by toddbaert** [comment]
I've opened https://github.com/open-feature/flagd-schemas/pull/131
