### ISSUE TITLE
[FEATURE] Create Shareable playground links

### ISSUE THREAD

**Issue by agardnerIT** [open-feature/flagd#1228]
### Requirements

The [flagd playground](https://flagd.dev/playground/) is great, but I find myself wishing I could create something there and then share what I've created with others.

Is this feasible?

**Comment by Kavindu-Dodan** [comment]
The current website is a static one. If we want to provide sharable links (see share feature here - https://go.dev/play/ ), we need a backend with a dedicated storage layer (a database). I don't think we have immediate plans to support this. 

cc - @beeme1mr & @toddbaert

**Comment by toddbaert** [comment]
> The current website is a static one. If we want to provide sharable links (see share feature here - https://go.dev/play/ ), we need a backend with a dedicated storage layer (a database). I don't think we have immediate plans to support this.
> 
> cc - @beeme1mr & @toddbaert

There's a simpler solution - encode the flag config in a URL query param. It would be long in some cases, but definitely doable. When the page loads, load the config from the URL, and when it's updated, update the URL.

**Comment by DBlanchard88** [comment]
ill take this one please

**Comment by toddbaert** [comment]
> ill take this one please

assigned

**Comment by toddbaert** [comment]
I neglected to mention in the description we probably need params for ALL the controls (flag key and eval type).
