### ISSUE TITLE
[FEATURE] Fractional Evaluation

### ISSUE THREAD

**Issue by beeme1mr** [open-feature/flagd#123]
## Overview

Fraction evaluation enable percentage based rollouts of a feature. It allows features to be tested pseudorandomly using a value from the evaluation context such as a targeting key.

The following example is how a configuration may look

```json
{
   "fib-algo":{
      "state":"ENABLED",
      "variants":{
         "recursive":"recursive",
         "memo":"memo",
         "loop":"loop",
         "binet":"binet"
      },
      "defaultVariant":"recursive",
      "targeting":{
         "if":[
            {
               "in":[
                  "@faas.com"
               ],
               "var":[
                  "email"
               ]
            },
            {
               "factionalEvaluation":[
                  {
                     "bucketBy":"email"
                  },
                  {
                     "distribution":[
                        [
                           "recursive",
                           25
                        ],
                        [
                           "memo",
                           25
                        ],
                        [
                           "loop",
                           25
                        ],
                        [
                           "binet",
                           25
                        ]
                     ]
                  }
               ]
            },
            null
         ]
      }
   }
}
```

The `factionalEvaluation` operation would be a custom operation in JSON logic that would return the variant name. The variant name would be selected based on the percentage (or fraction) defined in the distribution using a hash of the `flag key` and `bucketBy `value.

## Requirements:

- [ ] Factional evaluation is deterministic
- [ ] Targeting rules are compliant with the JSON logic spec
- [ ] An example config is added under config/samples
- [ ] Readme includes an example configuration

## Questions:

- Can bucketBy be optional and default to targetingKey?
- What should happen if the bucketBy value is invalid?
- What should happen if the percentage doesn't add up to 100?
- Should we use percentages or fractions?

## Links:

- https://observablehq.com/@kalebdf/a-b-testing-deterministic-bucketing

**Comment by toddbaert** [comment]
It's worth noting that distributions that aren't even splits should also be supported, ie: 


```
"factionalEvaluation": {
            "bucketBy": "email",
            "distribution": [
              {
                "variant": "recursive",
                "percentage": 50
              },
              {
                "variant": "loop",
                "percentage": 25
              },
              {
                "variant": "binet",
                "percentage": 25
              }
            ]
          }
```

**Comment by beeme1mr** [comment]
I updated the proposed flag configuration to better fit what JSON logic expects. I'm open to suggestions for how we can simplify this config since the current proposal is fairly complex.

**Comment by skyerus** [comment]
> Can bucketBy be optional and default to targetingKey?

Where does targetingKey come from? I can see it referenced [here](https://github.com/open-feature/flagd/blob/main/pkg/generated/server.gen.go#L17) but that struct isn't being used anywhere as far as I can tell.

> What should happen if the bucketBy value is invalid?

The default variant is returned and an error is logged.

> What should happen if the percentage doesn't add up to 100?

The default variant is returned and an error is logged.

> Should we use percentages or fractions?

I've gone with percentages, I think working with ints is better than floats.
