### ISSUE TITLE
[FEATURE] Unix socket support

### ISSUE THREAD

**Issue by james-milligan** [open-feature/flagd#124]
### Requirements

[OFEP](https://github.com/open-feature/research/blob/main/006-OFEP-flagd-sockets.md)

Requirements:

- [x] Create a socket path parameter within flagD
- [x] Implement uniform ctx cancellation for all services
- [x] `grpc_service.go` to support unix sockets through a new method that returns a net connection
- [x] Modifiy the existing `http_service` code to leverage a similar net connection start
- [x] Write tests

**Comment by james-milligan** [comment]
@AlexsJones is socket support for the `http_sevice` still part of the plan? Happy to take a look

**Comment by AlexsJones** [comment]
Go for it, should be quite quick to implement !
