### ISSUE TITLE
[BUG] panic when yaml file watchers are updated

### ISSUE THREAD

**Issue by toddbaert** [open-feature/flagd#1242]
### Observed behavior

flagd sometimes (~50% of the time) panics and crashes whena `.yaml` file it's watching is updated (note this DOES NOT seem to impact JSON payloads/files, and also doesn't impact payloads delivered over the wire).

```
2024-03-08T18:52:11.374Z        warn    evaluator/json.go:432   flag definition does not conform to the schema; validation errors:  1:(root): Invalid type. Expected: object, given: null         {"component": "evaluator", "evaluator": "json"}
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x93641d]

goroutine 32 [running]:
github.com/open-feature/flagd/core/pkg/evaluator.validateDefaultVariants(0xc000638668?)
        /src/core/pkg/evaluator/json.go:452 +0x1d
github.com/open-feature/flagd/core/pkg/evaluator.(*JSON).configToFlags(0xc0002225e0, {0xc000639b78, 0x4}, 0xc00009a0b8)
        /src/core/pkg/evaluator/json.go:447 +0x251
github.com/open-feature/flagd/core/pkg/evaluator.(*JSON).SetState(0xc0002225e0, {{0xc000639b78, 0x4}, {0xc0001309c0, 0x16}, 0x0})
        /src/core/pkg/evaluator/json.go:110 +0x5b6
github.com/open-feature/flagd/core/pkg/runtime.(*Runtime).updateWithNotify(0xc00038b930, {{0xc000639b78, 0x4}, {0xc0001309c0, 0x16}, 0x0})
        /src/core/pkg/runtime/runtime.go:124 +0xed
github.com/open-feature/flagd/core/pkg/runtime.(*Runtime).Start.func1()
        /src/core/pkg/runtime/runtime.go:52 +0x12d
golang.org/x/sync/errgroup.(*Group).Go.func1()
        /go/pkg/mod/golang.org/x/sync@v0.5.0/errgroup/errgroup.go:75 +0x56
created by golang.org/x/sync/errgroup.(*Group).Go in goroutine 1
        /go/pkg/mod/golang.org/x/sync@v0.5.0/errgroup/errgroup.go:72 +0x96
```

### Expected Behavior

flagd never crashes when an watched-file is updated.

### Steps to reproduce

- start flagd watching the yaml file below (`flagd start --uri file:./basic.yaml`)
- open the yaml file in an editor, and simple save it a few times (it's not even required to make changes, just trigger some fs events on the file)
- observe the stack trace above a substantial portion of times

The fact this doesn't happen every time indicates to me there's some kind of race, perhaps relating to the YAML conversion?

```
# basic.yaml
---
# yaml-language-server: $schema=https://flagd.dev/schema/v0/flags.json
flags:
  hex-color:
    state: ENABLED
    defaultVariant: red
    variants:
      green: "0a0"
      yellow: "aa0"
      red: "a00"
```

**Comment by dinhlockt02** [comment]
Hi, I'm interested in this project. Is it possible for me to take part in investigating this issue?

**Comment by Kavindu-Dodan** [comment]
> Hi, I'm interested in this project. Is it possible for me to take part in investigating this issue?

yes, feel free to work on this issue :)

**Comment by sagacioussid02** [comment]
I am a new contributor. I am not able to reproduce the issue: (attached video)

https://github.com/open-feature/flagd/assets/17208401/fdca2d0a-4922-4727-bce7-d34634cde323

**Comment by toddbaert** [comment]
@sagacioussid02 interesting... I wonder if it has to do with the OS you are on? I'm able to reproduce this easily on Linux.

@dinhlockt02 I guess based on your PR, you did see this behavior? What OS are you on? What environment are you using?

**Comment by dinhlockt02** [comment]
Yes, Interesting problem. I've watch @sagacioussid02 video and realised that this depends on os and editor.
Fact: I'm using ubuntu 22.04. The problem only occurs when I use vscode. If I use other editor (like gedit), the empty string is no more

For vs code
![image](https://github.com/open-feature/flagd/assets/20945393/853d204b-9b6c-45ac-bfd2-36c15f6c76ca)
For gedit
![image](https://github.com/open-feature/flagd/assets/20945393/8c1cc4cd-93ba-4ba9-a714-ce25716d08d7)

**Comment by toddbaert** [comment]
OK so this is a bit of an edge case, but still a valid fix, and there's probably other ways it can happen so this check is valid.
