### ISSUE TITLE
[BUG] Cannot connect to gRPC sync service of flagd

### ISSUE THREAD

**Issue by yangzhaox** [open-feature/flagd#1257]
### Observed behavior

I'm trying to test the new feature ` gRPC sync service` in flagd but failed to connect.

### Expected Behavior

I should be able to connect to the `gRPC sync service` in flagd successfully.

### Steps to reproduce

1. install the latest flagd (v0.9.1) on mac: 
    `brew install flagd`
3. start flagd with [demo.flagd.json](https://github.com/open-feature/flagd/files/14784511/demo.flagd.json): 
    `flagd start --uri file:./demo.flagd.json`
5. use postman to connect to gRPC with host `localhost:8015`, import the [sync_service.proto ](https://buf.build/open-feature/flagd/raw/main/-/sync/v1/sync_service.proto)file, run method `SyncFlags`
6. got the following error: 
    The operation you’re trying perform is not supported by the server. unknown service sync.v1.FlagSyncService.

**Comment by toddbaert** [comment]
Hey @yangzhaox , I think you're using the wrong proto if you're using the latest flagd version. That's an old, deprecated proto. Instead, use: https://buf.build/open-feature/flagd/raw/main/-/flagd/sync/v1/sync.proto

This has a different name and path (better namespacing). If you found some documentation pointing to this old file, please point us to it so we can update it.

**Comment by toddbaert** [comment]
Perhaps we can also add some comment so the deprecated proto to help.

**Comment by Kavindu-Dodan** [comment]
@toddbaert yes this is the main reason for grpc call to fail. Besides, I found a locking bug in the first implementation and this was fixed with the OFREP implementation. 

@yangzhaox could you please update to the latest flagd version[ 0.9.2](https://github.com/open-feature/flagd/pkgs/container/flagd/197057407?tag=v0.9.2) and use the correct proto for your Postman setup ?

**Comment by yangzhaox** [comment]
There seems to an option to enable the gRPC API reflection within flagd, with which .proto file is not required for Postman. What are the considerations of not doing it within flagd? Just curious.

**Comment by Kavindu-Dodan** [comment]
@yangzhaox  I assume you are referring to buf Connect protocol, which we use for RPC (remote) flag evaluations [1] [2]. 

We considered using buf Connect, however this is not compatible with a pure gRPC client, which we need for our in-process providers [3]. In-process mode can work with any sync service implementation where flagd being one such implementation and we didn't want to change this to buf Connect as this will be a major breaking change.  

[1] - https://flagd.dev/architecture/#rpc-evaluation
[2] - https://flagd.dev/quick-start/#evaluating-a-feature-flag 
[3] - https://flagd.dev/architecture/#in-process-evaluation

**Comment by yangzhaox** [comment]
Yeah, v0.9.2 works, thank you! @Kavindu-Dodan and @toddbaert! 

I'm very familiar with the differences between buf Connect protocol and gRPC, what I refers to is in Postman you have the option to load grpc service definition via `Server Reflection`. It doesn't work for flagd so I have to use .proto file instead. See the error below. 
<img width="757" alt="Screenshot 2024-03-28 at 9 41 09 AM" src="https://github.com/open-feature/flagd/assets/722332/6dbe9541-a848-450f-b48a-b7f1b22ab9cf">
<img width="763" alt="Screenshot 2024-03-28 at 9 41 42 AM" src="https://github.com/open-feature/flagd/assets/722332/cbb51ca1-884c-4516-8eef-16f598e00dd9">

**Comment by Kavindu-Dodan** [comment]
@yangzhao thanks for the reference, this is something I haven't come across before. And no, flagd gRPC sync service does not expose reflection [1]. We could consider this as a feature request but we will need to consider the implications it brings [2]

[1] - https://grpc.io/docs/guides/reflection/
[2] - https://grpc.io/docs/guides/reflection/#tips
