### ISSUE TITLE
[FEATURE] Support retrieving data from external services to enrich evaluation context

### ISSUE THREAD

**Issue by yangzhaox** [open-feature/flagd#1262]
### Discussed in https://github.com/open-feature/flagd/discussions/1251

<div type='discussions-op-text'>

<sup>Originally posted by **yangzhaox** March 19, 2024</sup>
When building a new feature and considering rolling it out to a large customer base in phases, there is requirement that certain customers who opt out any new features should be excluded permanently. The opt-out setting is usually stored in another config service which offers RESTful or GraphQL api access. There are other scenarios where we need to call services to get additional context data. Would it make sense to support this feature in flagd? @toddbaert </div>

**Comment by toddbaert** [comment]
@yangzhaox I want to be sure I understand.

Would this be for enriching the _context_ from an external call? Or enriching some placeholder values in the flag configuration?

If you want to enrich the evaluation context, [hooks](https://openfeature.dev/docs/reference/concepts/hooks) are the best means for this, and I think since flagd is built to work well with OpenFeature SDKs, we should avoiding adding functionality to flagd that can already be solved for with SDK features.

If you want to use some remote fetch result as the substitue for a variable in a flagd config, that seems like something we might want to consider supporting. For instance, considering a flagd defition like this:

```json
{
  "$schema": "https://flagd.dev/schema/v0/flags.json",
  "flags": {
    "enable-mainframe-access": {
      "state": "ENABLED",
      "defaultVariant": "false",
      "variants": {
        "true": true,
        "false": false
      },
      "targeting": {
        "if": [
          {
            "in": [
              {
                "var": "email"
              },
              ["todd@ingen.com", "mike@ingen.com"]
            ]
          },
          "true"
        ]
      }
    }
  }
}
```

Our new feature might reach out and populate the array of emails from an endpoint:

```json
{
  "$schema": "https://flagd.dev/schema/v0/flags.json",
  "flags": {
    "enable-mainframe-access": {
      "state": "ENABLED",
      "defaultVariant": "false",
      "variants": {
        "true": true,
        "false": false
      },
      "targeting": {
        "if": [
          {
            "in": [
              {
                "var": "email"
              },
              "$dynamicallyFetchedEmailsList"
            ]
          },
          "true"
        ]
      }
    }
  }
}
```
I hope that makes sense.

Which of these do you mean?

**Comment by yangzhaox** [comment]
Let me give you a concrete example. 

We want to evaluate a flag based on the logged-in user's type e.g. regular user or VIP user. This info is stored in a RESTful service e.g. `config-service`, which can be retrieved with a GET request passing the JWT (contains the current user's uuid). The example response looks like:
```
{ 
  "general": { 
    ...
    "type": "VIP",
    ...
  } 
}
``` 
And the flagd definition could look like:
```
{
  "$schema": "https://flagd.dev/schema/v0/flags.json",
  "flags": {
    "vip-only-access": {
      "state": "ENABLED",
      "defaultVariant": "false",
      "variants": {
        "true": true,
        "false": false
      },
      "targeting": {
        "if": [
          {
            "===": [
              {
                "var": "$configService.general.type"
              },
              "VIP"
            ]
          },
          "true"
        ]
      }
    }
  }
}
```

**Comment by thisthat** [comment]
Hey @yangzhaox, this is an interesting idea! 
I have, however, some concerns in implementing this into flagd. 
The main concern that I have is about performance. Feature Flag evaluations must be very quick and letting them do an external call will slow them down. I would rather see it this call in the business logic of the application more then in the Feature Flag evaluation domain. To evaluate this FF, your service has first to perform this call attaching the JWT token, so it can retrieve the type of your user. The type can then be added to the context evaluation of the FF. 
The second concern that I have is about maintenance efforts. We would need to support HTTP, HTTPS, gRPC, etc, compression on top of it (e.g., gzip, zstd), authentication, header forwarding, etc. Furthermore, we would need to support parsing of json, xml, arbitrary text, and so on and so forth. We should then provide default values for these external calls or how to handle errors generally. All of this is very application-specific and, I believe, not in the domain of Feature Flags.

**Comment by yangzhaox** [comment]
Hi @thisthat your concerns make total sense to me. However is it possible to define an extension point in flagd so the custom implementation of flagd can create  plugin (go code) to parse the evaluation context and make external API calls? With this approach flagd stays lightweight but offer additional flexibility for customization. What do you think?

**Comment by thisthat** [comment]
Hey @yangzhaox, that is a nice compromise. I talked about this with @toddbaert and he suggested re-use the interface that we have for [hooks](https://github.com/open-feature/go-sdk/blob/main/openfeature/hooks.go#L8) in the go-sdk. We could use https://pkg.go.dev/plugin to achieve this. Otherwise, it would also be interesting to explore a solution similar to the [OTel Collector builder](https://github.com/open-telemetry/opentelemetry-collector/tree/main/cmd/builder) where flagd can be configured to be built with pre-configured hooks and syncs 🤔

**Comment by toddbaert** [comment]
@Kavindu-Dodan @bacherfl what are your thoughts on [the above proposal](https://github.com/open-feature/flagd/issues/1262#issuecomment-2061805510)?

**Comment by Kavindu-Dodan** [comment]
From the example [1], the flagd flag is static and the only change is in the context data (ex:- `configService.general.type`).  From evaluation engine (flagd) point of view, it's responsibility of the caller to provide the context details relevant to the evaluation.

I think a better solution here would be to proxy flagd evaluations calls through a customized wrapper of the provider. This way, you don't have to worry about flagd's extensibility and you get the ability to do any customization per customer. 

![image](https://github.com/open-feature/flagd/assets/8186721/6e22507b-10df-4560-b0dc-cf3e4ce970ff)

This is doable and the only need is maintaining the custom wrapper provider at your org. 

[1] - https://github.com/open-feature/flagd/issues/1262#issuecomment-2030463161

**Comment by yangzhaox** [comment]
> From the example [1], the flagd flag is static and the only change is in the context data (ex:- `configService.general.type`). From evaluation engine (flagd) point of view, it's responsibility of the caller to provide the context details relevant to the evaluation.
> 
> I think a better solution here would be to proxy flagd evaluations calls through a customized wrapper of the provider. This way, you don't have to worry about flagd's extensibility and you get the ability to do any customization per customer.
> 
> ![image](https://private-user-images.githubusercontent.com/8186721/326986192-6e22507b-10df-4560-b0dc-cf3e4ce970ff.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ3NTMxMDIsIm5iZiI6MTcxNDc1MjgwMiwicGF0aCI6Ii84MTg2NzIxLzMyNjk4NjE5Mi02ZTIyNTA3Yi0xMGRmLTQ1NjAtYjBkYy1jZjNlNGNlOTcwZmYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUwMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MDNUMTYxMzIyWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9Zjg3NjRhYTg3N2UwNGVlNmNlZDg2YjcyZWZhMjI1NGQzNGQ0Y2EzNjM2ZmEzNjBiNDAzMzdkNzcyMDA0N2YxMiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.dQ_1_yXkTihVgl1OGPvkI9pclohDZ610n042w02YncI)
> 
> This is doable as providers are essentially an Interface implementation. The only downside is maintaining the custom wrapper provider at your org. You can have any strategy to perform your external configuration fetch (i,e - GraphQL query, JWT parsing, SQL query etc.. )
> 
> Plugin package, I am not convinced about this solution after going through the long warning list [2] For example `Runtime crashes are likely to occur unless all parts of the program (the application and all its plugins) are compiled using exactly the same version of the toolchain, the same build tags, and the same values of certain flags and environment variables.` sounds bad
> 
> [1] - [#1262 (comment)](https://github.com/open-feature/flagd/issues/1262#issuecomment-2030463161) [2] - https://pkg.go.dev/plugin#hdr-Warnings

Hi @Kavindu-Dodan thank you for the suggestion, I think what you mean is [provider hooks](https://openfeature.dev/docs/reference/concepts/hooks). I fully agree with you if there is only 1 or few consumers of flagd service. In our case, we have 10 ~ 100 consumers who request the support of this feature and the language they use are different, e.g Kotlin, Go, Python, Java, Javascript.

**Comment by beeme1mr** [comment]
I'm concerned about the complexity this will add to flagd. Perhaps something like a [gRPC proxy](https://github.com/mwitkow/grpc-proxy) could be built to enrich the request before it hits flagd.

**Comment by Kavindu-Dodan** [comment]
> I'm concerned about the complexity this will add to flagd. Perhaps something like a [gRPC proxy](https://github.com/mwitkow/grpc-proxy) could be built to enrich the request before it hits flagd.

Yeah, I am also with this view. We should keep flagd simple and lightweight as possible. And focus on the flag evaluations based on defined flag sources. 

> Hi @Kavindu-Dodan thank you for the suggestion, I think what you mean is [provider hooks](https://openfeature.dev/docs/reference/concepts/hooks).

You can consider as a hook but more specifically what I proposed is a custom flagd provider wrapper (say java flagd provider, so java flagd wrapper for your org). This wrapper then can contain any custom initialization logic and like in your example, can contain an API call to retrieve some context information. If you take this path, instead of customization per service, you only need language-specific flagd provider wrappers. And each service that use flagd for feature flagging can use the wrapper provider with context enrichment.

**Comment by beeme1mr** [comment]
A tool called Pocketbase lets you add custom hooks. Perhaps we could do something similar. FYI @Kavindu-Dodan 

https://pocketbase.io/docs/go-overview/
