### ISSUE TITLE
[BUG] Wrong $defs keyword used in JSON schemas

### ISSUE THREAD

**Issue by dt-rendstrasser** [open-feature/flagd#1309]
### Observed behavior

[docs/schema/v0/flags.json](https://github.com/open-feature/flagd/blob/34756fe02d16e62e12b9baf65e983cd4157fa89e/docs/schema/v0/flags.json#L146) and [docs/schema/v0/targeting.json](https://github.com/open-feature/flagd/blob/34756fe02d16e62e12b9baf65e983cd4157fa89e/docs/schema/v0/targeting.json#L342) use the `$defs` keyword.

Both JSON schemas use version `draft-07` based on the `$schema` setting. 

A quick look at Google shows that the `$defs` keyword is not part of the `draft-07` version. Back then, it was named `definitions`. E.g., see [https://opis.io/json-schema/2.x/definitions.html](https://opis.io/json-schema/2.x/definitions.html).

Some json-schema-validators like [com.networknt.json-schema-validator](https://github.com/networknt/json-schema-validator) write warning logs by default if unknown keywords are encountered. This is exactly what happens in this case with this validator:
```
c.n.schema.UnknownKeywordFactory         : Unknown keyword $defs - you should define your own Meta Schema. If the keyword is irrelevant for validation, just use a NonValidationKeyword or if it should generate annotations AnnotationKeyword
```

### Expected Behavior

Would it be possible to use `definitions` instead of `$defs` for as long as the JSON schema version is `draft-07`?
Affected JSON schemas:
* [docs/schema/v0/flags.json](https://github.com/open-feature/flagd/blob/34756fe02d16e62e12b9baf65e983cd4157fa89e/docs/schema/v0/flags.json#L146) 
* [docs/schema/v0/targeting.json](https://github.com/open-feature/flagd/blob/34756fe02d16e62e12b9baf65e983cd4157fa89e/docs/schema/v0/targeting.json#L342)

**Comment by beeme1mr** [comment]
Thanks for bringing this up, @dt-rendstrasser. [Here's a direct link](https://json-schema.org/draft-07/draft-handrews-json-schema-validation-01#rfc.section.9) to the spec that confirms that `definitions` is still valid in newer versions of the spec but `$defs` has superseded it.

**Comment by toddbaert** [comment]
I will confirm and implement this and if all works as expected I will release a fix. Standby.

**Comment by toddbaert** [comment]
Pulling this into the flagd provider for Java: https://github.com/open-feature/java-sdk-contrib/pull/789
