### ISSUE TITLE
[FEATURE] Allow flagd debug flag to be set through environment variable

### ISSUE THREAD

**Issue by Kavindu-Dodan** [open-feature/flagd#1323]
**Background**

flagd `debug` flag is defined at the root level and available as a persistent flag. However persistent flags are not modifiable through environment variables.

**Requirement**

Given flagd support environment variable-based configurations, we should add support to define debug flag through environment variable (ex:- `FLAG_DEBUG` or `DEBUG`)

Also consider the following,

- Given we haven't visited cobra and viper configurations for a long time, it could be a good opportunity to refactor flagd startup setup
- Document `FLAGD` prefix based environment variable resolving capability

**Comment by snosratiershad** [comment]
I'm taking this issue
