### ISSUE TITLE
[BUG] Errors occured when execute flag install step 

### ISSUE THREAD

**Issue by warjiang** [open-feature/flagd#1350]
### Observed behavior

I follow the step in section **Go binary** , links 👉🏻 https://flagd.dev/installation/#summary
![image](https://github.com/open-feature/flagd/assets/6478745/3be98ba1-0794-434c-9143-a378876b7229)
But some errors occured: 
![image](https://github.com/open-feature/flagd/assets/6478745/7b96c575-0315-4761-abcc-a6eb7019e796)
Here is the original errors:
```
go install github.com/open-feature/flagd/flagd@latest

# github.com/open-feature/flagd/flagd/pkg/service/flag-evaluation/ofrep
.gvm/pkgsets/go1.22.5/global/pkg/mod/github.com/open-feature/flagd/flagd@v0.11.0/pkg/service/flag-evaluation/ofrep/handler.go:75:54: undefined: ofrep.BulkEvaluationContextError
.gvm/pkgsets/go1.22.5/global/pkg/mod/github.com/open-feature/flagd/flagd@v0.11.0/pkg/service/flag-evaluation/ofrep/handler.go:80:22: assignment mismatch: 2 variables but h.evaluator.ResolveAllValues returns 1 value
.gvm/pkgsets/go1.22.5/global/pkg/mod/github.com/open-feature/flagd/flagd@v0.11.0/pkg/service/flag-evaluation/ofrep/handler.go:84:47: too many arguments in call to ofrep.BulkEvaluationContextErrorFrom
	have (string, string)
	want ()
# github.com/open-feature/flagd/flagd/pkg/service/flag-sync
.gvm/pkgsets/go1.22.5/global/pkg/mod/github.com/open-feature/flagd/flagd@v0.11.0/pkg/service/flag-sync/sync-multiplexer.go:166:14: assignment mismatch: 2 variables but r.store.GetAll returns 1 value
# github.com/open-feature/flagd/flagd/pkg/service/flag-evaluation
.gvm/pkgsets/go1.22.5/global/pkg/mod/github.com/open-feature/flagd/flagd@v0.11.0/pkg/service/flag-evaluation/flag_evaluator.go:73:17: assignment mismatch: 2 variables but s.eval.ResolveAllValues returns 1 value
.gvm/pkgsets/go1.22.5/global/pkg/mod/github.com/open-feature/flagd/flagd@v0.11.0/pkg/service/flag-evaluation/flag_evaluator.go:336:28: undefined: model.GetErrorMessage
.gvm/pkgsets/go1.22.5/global/pkg/mod/github.com/open-feature/flagd/flagd@v0.11.0/pkg/service/flag-evaluation/flag_evaluator_v2.go:71:17: assignment mismatch: 2 variables but s.eval.ResolveAllValues returns 1 value
```

### Expected Behavior

the flagd binary can be installed in the bin fold for go

### Steps to reproduce

execute `go install github.com/open-feature/flagd/flagd@latest`

BTW, after diving into the code for the latest tag, which is `flagd@v0.11.0`
![image](https://github.com/open-feature/flagd/assets/6478745/cb28f044-4c6d-4c72-b519-325585cf03c0)

the `flagd` use `ofrep.BulkEvaluationContextError()` in `core` pkg
![image](https://github.com/open-feature/flagd/assets/6478745/ad870929-4fad-4d97-b4df-7381ef954f37)

But the `core` pkg doesn't contains `ofrep.BulkEvaluationContextError()` for version `core/v0.9.3`
![image](https://github.com/open-feature/flagd/assets/6478745/c9c01ebe-54dd-4f8b-bc25-894bac097ff3)

`ofrep.BulkEvaluationContextError()` doesn't occurs in core pkg until for `core/v0.10.0`

So the main branch is right, but still now the lastet tag for `github.com/open-feature/flagd/flagd` is wrong

**Comment by toddbaert** [comment]
Oh thanks for bringing this to our attention! I think the docker container is the most popular means of using flagd, but we certainly want the bin install to work as well.

> So the main branch is right, but still now the lastet tag for github.com/open-feature/flagd/flagd is wrong

Then seems like a new release will fix this: https://github.com/open-feature/flagd/pull/1341

cc @Kavindu-Dodan

**Comment by Kavindu-Dodan** [comment]
Unfortunately, this is due to the specific go install usage, where flagd module's go.mod file is considered for dependencies. Our image builds use go workspaces, so all submodules of core package (flagd & proxy) use latest core components. 

@toddbaert  yeah the release will fix this. But we may need to revisit and release **core** and **flagd** independently if we wants to promote binary installations 🤔

**Comment by warjiang** [comment]
> go install github.com/open-feature/flagd/flagd@latest

sorry late for the reply, with the latest version ,it works on my desktop:
<img width="1317" alt="image" src="https://github.com/user-attachments/assets/d0db6f9f-c571-4e86-8980-c526542eabc3">
thanks~
