### ISSUE TITLE
[DOC] flagd-proxy example invalid url 

### ISSUE THREAD

**Issue by kustoffigor** [open-feature/flagd#1362]
### Change in the documentation

https://github.com/open-feature/flagd/tree/main/flagd-proxy here is line
    - '[{"uri":"grpc://flagd-proxy-svc.flagd-proxy.svc.cluster.local:8015","provider":"grpc","selector":"core.openfeature.dev/NAMESPACE/NAME"}]'

The problem is that it works without grpc:// in the url and doesn't work with grpc://. Just tested it,

**Comment by beeme1mr** [comment]
Thanks, I've updated the docs.

https://github.com/open-feature/flagd/commit/4911697ab1fb2b12f8d4b552b734ef9c3d43fb16
