### ISSUE TITLE
[DOC] Monitoring metrics are misnamed

### ISSUE THREAD

**Issue by agardnerIT** [open-feature/flagd#1371]
### Change in the documentation

[This page](https://flagd.dev/reference/monitoring/#metrics) shows:

flagd expose following metrics,

```
http.server.duration
http.server.response.size
http.server.active_requests
feature_flag.flagd.impression
feature_flag.flagd.evaluation.reason
```

1) Typo: `expose` should be `exposes`
2) The metrics are misnamed:
    - `http.server.duration` is actually `# TYPE http_server_duration_seconds histogram`
    - `http.server.response.size` is actually `# TYPE http_server_response_size_bytes histogram`
    - `http.server.active_requests` is actually `# TYPE http_server_active_requests gauge`
    - `feature_flag.flagd.impression` is actually `# TYPE feature_flag_flagd_impression_total counter`
    - `feature_flag.flagd.evaluation.reason` is actually `# TYPE feature_flag_flagd_evaluation_reason_total counter`
 3) We should consider adding a line to this page to say "These metrics will only appear **after** the first flag evaluation"

**Comment by beeme1mr** [comment]
Hey @agardnerIT, I've fixed the typos. The documented metric names are correct and follow OTel's recommended naming convention. However, Prometheus, Dynatrace, and likely others have different metric naming requirements. I've added a disclaimer that the metric names may be transformed by the consuming monitoring tool.
