### ISSUE TITLE
[Web-support] Support CORS (or document that it should be implemented in LB)

### ISSUE THREAD

**Issue by toddbaert** [open-feature/flagd#168]
If we want to allow flagd instances to be exposed publicly (for web use-cases), we will want to have some support (or at least guidance for CORS).

See thread [here](https://github.com/open-feature/flagd/pull/163/files#r976393919)

>I think there IS some possible DDoS protection here... If I infected a number of web pages (or host malicious web pages) that call a flagd I want to attack, I can use my origin/infected web page to tell other users to spam that flagd target, adding load to it in a DDoS. Though I could attack flagd directly, my malicious origin is making my users attack that flagd too. CORS actually could help us with this, since a flagd would deny pre-flight requests from my hostile origins.

**Comment by toddbaert** [comment]
> Can you please in some detail explain the architecture you anticipate here? People serving this on a VIP via cluster IP on the internet? In almost any production environment I would anticipate at least a single level of load balancing reverse proxy which would be a more appropriate place to take care of this.

Like I mentioned in the linked thread, I fully agree this is best handle with an LB or some reverse proxy, which is why I'm fine with the solution being some simple documentation saying so if we eventually document a web-architecture.

I simply didn't want to lose track of this concern.

**Comment by toddbaert** [comment]
If you think this isn't worth discussing or keeping open until we have a web-architecture, feel free to close.

**Comment by AlexsJones** [comment]
Okay, we can refer to this for posterity.
