### ISSUE TITLE
[BUG] FlagD returns exit code zero on error

### ISSUE THREAD

**Issue by beeme1mr** [open-feature/flagd#169]
### Observed behavior

FlagD returns exit code zero on error

### Expected Behavior

FlagD should return a non-zero exit code when an error occurs.

### Steps to reproduce

1. Run `docker run -p 8013:8013 -it ghcr.io/open-feature/flagd:v0.1.0 start --uri /invalid/path.json`
2. Run `echo $?`

**Comment by AlexsJones** [comment]
https://github.com/open-feature/flagd/pull/170

**Comment by toddbaert** [comment]
Closed with https://github.com/open-feature/flagd/pull/170
