### ISSUE TITLE
Create integration test suite

### ISSUE THREAD

**Issue by toddbaert** [open-feature/flagd#176]
We should write a test suite that implements the gherkins integration test suite: https://github.com/open-feature/test-harness/blob/main/features/evaluation.feature

We should run the tests against a test image built in the ci to catch issues like this: https://github.com/open-feature/flagd/pull/174

**Comment by skyerus** [comment]
The go-sdk implements the gherkins integration test suite using flagd as its provider. The CI process runs the suite against the most recent release of flagd. As such, we can achieve our aim by leveraging the same test suite in flagd's CI.

I'd opt against exporting it directly from go-sdk (needlessly increasing the surface area of go-sdk), instead extract it to a new module in go-sdk-contrib, which could subsequently be imported by go-sdk and flagd's testing packages.
