### ISSUE TITLE
[FEATURE] Should "flags" be an array?

### ISSUE THREAD

**Issue by agardnerIT** [open-feature/flagd#178]
### Requirements

Shouldn't `flags` be an array?

```
{
 "flags": [{
    "myBoolFlag": {
      ...
    },
   "myStringFlag": {
      ...
    }
  }]
}
```

**Comment by skyerus** [comment]
Having the `flags` as an object provides the benefits of being indexable by flag name and enforcing no duplicates.
What's the use case for the flags being an array instead of an object?

**Comment by beeme1mr** [comment]
As @skyerus mentioned, this data structure provides a number of benefits over an array. The main benefits being uniqueness guarantees and performance.

**Comment by toddbaert** [comment]
From a basic data structure perspective, you use arrays when you want to iterate, and hashmaps (which are what JSON objects are in most languages) when you want to pluck. Flag evaluations are "plucks" fundamentally, not iterations.

**Comment by agardnerIT** [comment]
Makes total sense if flags are unique, as they would be with a single flagd instance. Blame my lack of flagd knowledge before opening this. I shall read more before jumping in in future :)
