### ISSUE TITLE
[BUG] flagd doesn't reindex flags on delete

### ISSUE THREAD

**Issue by agardnerIT** [open-feature/flagd#181]
### Observed behavior

Changing a flag key while flagd is running doesn't reindex the available flags and the old value is returned until `flagd` is restarted.

Adding new flags **does** work

### Expected Behavior

Adding and removing flags is entirely dynamic and the JSON file is always the source of truth.

### Steps to reproduce

Create a JSON file:

```
{
    "flags": {
      "foo": {
        "state": "ENABLED",
        "variants": {
          "value": "baz"
        },
        "defaultVariant": "value"
      }
    }
}
```

Which (correctly) returns `baz`.

Now change `"foo": {` to `"foo2": {` and re-execute the retrieval of `foo`. I'd expect a "no flag found" error or similar, but I still get `baz`.

Restart the `flagd` process and `foo` is no longer found (which is the correct behaviour).

-----
Alternatively, run `flagd` and (while it is running) add a new flag called `foo3`. Now get `foo3` and that works. Proving that adding dynamically works but deleting doesn't.

**Comment by AlexsJones** [comment]
Thank you for submitting the bug, I suspect this is to do with the way we merge JSON schema together. 

https://github.com/open-feature/flagd/blob/e13caeaf02e384c3a904d0daad4b0aa951be54c3/pkg/eval/json_evaluator.go#L40

@skyerus @toddbaert thoughts?

**Comment by toddbaert** [comment]
Ya I think the merge was originally implemented without really thinking about flags being removed.
