### ISSUE TITLE
[Examples] Help wanted developing examples that consume Flagd

### ISSUE THREAD

**Issue by AlexsJones** [open-feature/flagd#19]
We need to exemplify how you can take a C/Go/Rust process and plug it into FlagD through either the restful or socket provider.

**Comment by beeme1mr** [comment]
Here's a PR for a flagD golang provider.

https://github.com/open-feature/golang-sdk-contrib/pulls

**Comment by beeme1mr** [comment]
- [FlagD JS](https://github.com/open-feature/js-sdk-contrib/tree/main/libs/providers/flagd)
- [FlagD Java](https://github.com/open-feature/java-sdk-contrib/tree/main/providers/flagd)
- [FlagD Go](https://github.com/open-feature/go-sdk-contrib/tree/main/providers/flagd)
