### ISSUE TITLE
Run the Trivy scan on a schedule

### ISSUE THREAD

**Issue by beeme1mr** [open-feature/flagd#196]
## Overview

Currently, a Trivy scan runs when a PR is opened or modified. That means detection of a day two vulnerability can block PRs that have nothing to do with dependencies. An example can be seen [here](https://github.com/open-feature/flagd/pull/195/checks?check_run_id=8998297233).

## Proposal

Move the Trivy scan to a dedicated workflow that runs on a schedule. The scan can continue to run on PRs but only when dependencies are changed.

**Comment by AlexsJones** [comment]
Can you run a cron on github actions? Wouldn't this take a proper CI/CD?

**Comment by beeme1mr** [comment]
Yes, it's possible to run on a cron schedule.

https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#schedule
