### ISSUE TITLE
[FEATURE] package specific no-op logging

### ISSUE THREAD

**Issue by james-milligan** [open-feature/flagd#214]
### Requirements

To improve performance we should be able to disable logging packages within flagd, such as disabling the logging for the `service` while preserving those from `runtime` and `sync`, this no-op logging implementation should also bypass the setting of fields on the logger, bypassing the `sync.Map` and further improving the performance
This can be done through arguments such for example `--disable-service-logging` or `--logger-args=disable-service-logging`

**Comment by toddbaert** [comment]
Yep, I think this is needed. Any opinions on if this no-op logging should be the default with the operator?

**Comment by james-milligan** [comment]
> Yep, I think this is needed. Any opinions on if this no-op logging should be the default with the operator?

This is now the default behaviour as this feature is controlled via the `--debug`
