### ISSUE TITLE
Configuration changes take affect immediately

### ISSUE THREAD

**Issue by beeme1mr** [open-feature/flagd#22]
## Summary

One of the main benefits of feature flags is the ability to change values at runtime. Flagd needs to watch for feature flag configuration changes and update its internal state. This should happen without downtime to Flagd.

## Considerations

 - File system watcher overhead should be minimal
 - Change events may be added to the OpenFeature spec in the future

## Questions

- How should invalid feature flag configuration changes be handled in a running process?

## Resources

 - [Confd](https://github.com/kelseyhightower/confd)
 - [fsnotify](https://github.com/fsnotify/fsnotify)

**Comment by AlexsJones** [comment]
The current implementation is more or less on request, would this satisfy the requirement?

**Comment by beeme1mr** [comment]
Yeah, that's fine for now. Long term I think we would want to only reload the config if the file has changed.

**Comment by beeme1mr** [comment]
A downside of reloading the file per request besides overhead is that flagd wouldn't be able to push events. That's currently out of scope but will likely be added to the OpenFeature spec soon.

**Comment by AlexsJones** [comment]
Okay, so the sync could be reworked into an informer/watcher then each implementation has to do what it will with that.

**Comment by AlexsJones** [comment]
This has been reworked with notifiers
