### ISSUE TITLE
[FEATURE] flagd bulk evaluation

### ISSUE THREAD

**Issue by toddbaert** [open-feature/flagd#234]
### Requirements

In order to support synchronous evaluation (something particularly important for [client use cases](https://github.com/open-feature/spec/issues/167)), we need a bulk evaluation endpoint in flagd. The endpoint would accept a `context` and evaluate all configured flags with that `context`. The returned result should be a map of `flagKey: resolutionDetails`.

- [x] update schema (https://github.com/open-feature/schemas/issues/63)
- [x] implement function
- [ ] add tests
- [x] add documentation

Example curl:

```shell
curl -X POST "localhost:8013/schema.v1.Service/ResolveAll" -d '{"context":{"email": "foo@bar.com"}}' -H "Content-Type: application/json"

{
   "flag1":{
      "value":"#0000FF",
      "reason":"TARGETING_MATCH",
      "variant":"blue"
   },
   "flag2":{
      "value":false,
      "reason":"STATIC",
      "variant":"on"
   }
}

```

Things to consider:

- possible enhancements in the future to allow an array of flag keys to evaluate, instead of all
- should we include additional metadata such as flag type to aid in parsing?

**Comment by beeme1mr** [comment]
Depends on https://github.com/open-feature/open-feature-operator/issues/291
