### ISSUE TITLE
[FEATURE] EventStreamResponse optimization

### ISSUE THREAD

**Issue by james-milligan** [open-feature/flagd#238]
### Requirements

When multiple flags are updated simultaneously flagd sends multiple `configuration_change` events with the following structure:
```
{
  "type": "configuration_change",
  "data": {
    "type": "delete",
    "source": "file:config/samples/example_flags.json",
    "flagKey": "myBoolFlag"
  }
}
```
These events should be consolidated into one single configuration change event.
for example:
```
{
  "type": "configuration_change",
  "data": {
    "flags": {
      "myBoolFlag": {
        "type": "delete",
        "source": "file:config/samples/example_flags.json"
      },
      "myStringFlag": {
        "type": "update",
        "source": "file:config/samples/example_flags.json"
      }
    }
  }
}
```

These changes should be made in the `updateState` method found in `pkg/runtime/runtime.go`

**Comment by beeme1mr** [comment]
Including the flag type makes sense to me. 👍

**Comment by skyerus** [comment]
As we are opting for the approach of a singular cache map for all flag types, receiving a flag's type in the event is now redundant. This is perhaps another benefit in favour of the one cache map to rule them all.
