### ISSUE TITLE
[FEATURE] Consider an "evaluator" context for auditing & access control purposes

### ISSUE THREAD

**Issue by Kavindu-Dodan** [open-feature/flagd#245]
Originally discussed through https://github.com/open-feature/ofep/issues/42 

### Requirements

Feature Flag evaluation audits could be a security requirement for auditing purposes. For such audits, it is desired to have details on the entity that invoked the evaluation.

For server-side invocations, this could be a simple server application identifier. For client-side invocations, this could consist of numerous identifiers such as application id, browser vendor, IP or a unique identifier that sperate one client from another. For both cases, this could be even a session ID or a token.

Further, if implemented correctly, this identification could be utilized to enforce an access control mechanism.

**Comment by beeme1mr** [comment]
Closing this issue since the originating OFEP was closed.
