### ISSUE TITLE
[BUG] Benchmarks are failing silently

### ISSUE THREAD

**Issue by skyerus** [open-feature/flagd#248]
### Observed behavior

In the build github ci pipeline the `Run benchmark` step in the  `Run Benchmark` job is reporting errors (as seen [here](https://github.com/open-feature/flagd/actions/runs/3846072023/jobs/6550952103)) but the step is passing.

### Expected Behavior

The benchmarks should pass and in cases where there are failures the benchmark step should fail.

**Comment by Kavindu-Dodan** [comment]
Seems to be coming with caching introduction, [1]

```
      expected: "DEFAULT"
      actual  : "STATIC"
```

[1] https://github.com/open-feature/flagd/actions/runs/3846072023/jobs/6550952103#step:4:123
