### ISSUE TITLE
[Feature] Create specific loggers for sync/services

### ISSUE THREAD

**Issue by AlexsJones** [open-feature/flagd#29]

**Comment by toddbaert** [comment]
@AlexsJones can you elaborate a little bit on the intent of this issue?

**Comment by AlexsJones** [comment]
This is to pass a sub logger from logrus per service, it's a convenience that prefixes log entries

**Comment by beeme1mr** [comment]
@james-milligan can this issue be closed?

**Comment by james-milligan** [comment]
Not as of yet, currently I believe sync/services are using the default log from logrus

**Comment by AlexsJones** [comment]
I can look at this or someone else, basically we need to branch out sub loggers into the components, it's not a huge deal of work just a bit of plumbing

**Comment by AlexsJones** [comment]
https://github.com/open-feature/flagd/pull/92
