### ISSUE TITLE
[FEATURE] Make HTTP sync frequency configurable

### ISSUE THREAD

**Issue by Kavindu-Dodan** [open-feature/flagd#293]
### Requirements

Current HTTP flag sync is backed by a cron job and it has hardcoded sync frequency to "every 5th minute"  - `*/5 * * * *`.

It is desired to have configurability on this frequency so that individual flagd users can deploy flagd with desired sync frequencies. 

#### Expected outcome

-  A new configuration option to override the default for HTTP sync frequency and use it in the cron job
-  Documentation on the option as well as default value

**Comment by OsamaNabih** [comment]
Hey there. I'm just getting familiar with CNCF and thought this might be a good issue for me.
What granularity are you expecting for the frequency? Just the minutes, or could it be more?
As for the exposing the configurations, will this be through the flags, config file, env variables, or all of them?

**Comment by OsamaNabih** [comment]
Hey
I made a branch with some initial code adjustments, however I do not have permission to push it.
I could not find any links on how an outsider could start contributing.
Is there a way for me to create a PR on this?

**Comment by OsamaNabih** [comment]
I created an initial PR.
Please review it and provide your feedback
Thank you
https://github.com/open-feature/flagd/pull/404
