### ISSUE TITLE
[REFACTOR] Unify case usage, seperators and punctuation for logging

### ISSUE THREAD

**Issue by Kavindu-Dodan** [open-feature/flagd#298]
### Requirements

Flagd logs have mixed usage of uppercase and lowercase. 

`je.Logger.Error(fmt.Sprintf("parseFractionalEvaluationData: %v", err))` vs `fs.Logger.Error(fmt.Sprintf("Error fetching after Create notification: %s", err.Error()))`

This issue focuses on unifying case usage throughout the source and setting the standards for logging formats. 

- Prefered first letter case - **lowercase** 

    ex:- fs.Logger.Debug("configuration modified")

- Prefered separator for details - **:**

   (Note the `:` usage for for uri detail )
   ex:- Logger.Info(fmt.Sprintf("watching filepath: %s", fs.URI))

- Prefer log line end punctuation - NONE (i.e - No full stop)

   ex:- fs.Logger.Info("Starting filepath sync notifier")

**Comment by mihirm21** [comment]
Hi, can I be assigned this issue

**Comment by beeme1mr** [comment]
Sure, thanks @mihirm21!

**Comment by mihirm21** [comment]
Could this be merged though DCO not permitting since I am unable to sign off my commit.

**Comment by mihirm21** [comment]
plz check my PR
