### ISSUE TITLE
Automatically bump version in Homebrew

### ISSUE THREAD

**Issue by beeme1mr** [open-feature/flagd#306]
## Overview

Flagd was recently [added to Homebrew](https://github.com/Homebrew/homebrew-core/pull/120187). The currently deployed version is [3.1](https://github.com/Homebrew/homebrew-core/pull/120541). This could quickly become out of sync if the update process isn't automated.

## Proposal

Add an additional step in [the release process](https://github.com/open-feature/flagd/blob/main/.github/workflows/release-please.yaml) to automatically open a PR in the [homebrew-core repo](https://github.com/Homebrew/homebrew-core).

## Resources

- https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md#to-submit-a-version-upgrade-for-the-foo-formula
- https://github.com/mislav/bump-homebrew-formula-action

**Comment by josecolella** [comment]
@beeme1mr It seems that homebrew already provides the functionality for us: https://github.com/Homebrew/homebrew-core/pull/121354#issuecomment-1401234491

**Comment by SMillerDev** [comment]
No, that comment indicates that there is a way to get the latest project version. A livecheck does not provide a method to automatically update.

**Comment by chenrui333** [comment]
livecheck and bump process are two separate things.

> https://github.com/mislav/bump-homebrew-formula-action

That would handle the bump process as part of the release process.

**Comment by josecolella** [comment]
@beeme1mr Since @chenrui333 already has the PR out, we can assign this him
