### ISSUE TITLE
[DOC] flagd provider docs

### ISSUE THREAD

**Issue by beeme1mr** [open-feature/flagd#334]
### Change in the documentation

Create documentation that explains how a new provider can be developed. This can be referenced by new and existing flagd providers to ensure a consistent experience across technologies.

Areas to include:

- Responsibilities of a flagd provider
- Where to find the protobuf definitions
- How to generate a client library using Buf
- Caching recommendations
- Recommended environments variables
- How to handle failure conditions
- Design considerations

**Comment by toddbaert** [comment]
I would also add a link to the general provider recommendations/FAQ: https://docs.openfeature.dev/docs/reference/concepts/provider#faq

Does `Recommended environments variables` mean standard ENV vars and config overriding?

Otherwise, this sounds good.
