### ISSUE TITLE
[DOC] Add Troubleshooting Section for HTTP2

### ISSUE THREAD

**Issue by beeme1mr** [open-feature/flagd#362]
### Change in the documentation

An error message such as `Received unexpected EOS on empty DATA frame from server` on the client that called flagd may mean that HTTP2 is not allowed in the network. In Kubernetes, setting the `appProtocol` to `grpc` may resolve the issue.

https://istio.io/latest/docs/ops/configuration/traffic-management/protocol-selection/

**Comment by toddbaert** [comment]
I think we should take this opportunity to add a "troubleshooting" section to the docs that can be easily linked to from low-level errors such as this.

@beeme1mr if you agree, please update the description accordingly.
