### ISSUE TITLE
[DOUBT] regarding future project ideas 

### ISSUE THREAD

**Issue by mihirm21** [open-feature/flagd#373]
Hi, I am Mihir Mittal, a sophomore at the Indian Institute of Technology, Kanpur, majoring in Mathematics and Scientific Computing. 
My relevant skills include development in Golang, good knowledge of DSA, and linear algebra among others. https://github.com/mihirm21/CF-Stress- This was one of the repositories I made last summer related to the backend of a stress testing tool for competitive programming to provide the smallest failing test case in Golang.
I was interested in contributing to the open-feature project under Google Summer of Code 2023. I even had 1 PR merged #322  last week. So what I wanted to ask was whether open-feature is participating this year under CNCF for GSoC and if yes, could you please provide some project ideas/bugs on which I could start ideating for implementations.
Hoping to have a positive reply.

**Comment by beeme1mr** [comment]
Hey @mihirm21, I'm looking into what would be required on our side to support GSoC. It's not something we've done in the past but it does seem like a great program that's mutually beneficial. I'll just need to determine what kind of time commitment is required before committing to anything specific.

Regardless of GSoC, we'll try and create more issues with a `good-first-issue` and/or `help-wanted` label. We need to get better about creating issues geared towards new contributors but for now there are a handful of open issues. You can see the list [here](https://github.com/issues?q=is%3Aissue+is%3Aopen++archived%3Afalse+sort%3Aupdated-desc+user%3Aopen-feature+label%3A%22good+first+issue%22+).

**Comment by beeme1mr** [comment]
Hi @mihirm21, I wanted to provide a quick update here. We're working on identifying some good topics and mentors for GSoC. Do you have a particular area of interest? That would help us identify a good fit you.

**Comment by mihirm21** [comment]
My interest areas include applied mathematics and data science applications. Also has a good knowledge of data structures and algorithms. Particularly interested to work in backend development which help add some feature/reduce computation times for some particular operations/testing etc.

**Comment by beeme1mr** [comment]
OpenFeature is participating the GSoC. You can find the project proposals [here](https://github.com/cncf/mentoring/blob/main/summerofcode/2023.md#openfeature).
