### ISSUE TITLE
[FEATURE] Support Health and Readiness Probes in flagd

### ISSUE THREAD

**Issue by beeme1mr** [open-feature/flagd#408]
## Overview

In production environments, feature flags may be considered a mission critical service that must be available. It's important for flagd to expose a means for Kubernetes to know when the container is ready to perform flag evaluation. Also, needs to be aware if flagd is in an unhealth state so that it can take corrective measures. These settings should be configurable so that a Kubernetes cluster administrator can decide various error conditions should be handled.

## Requirements

- [x] Conduct research on the pros and cons of adding health and readiness probes.
- [x] Add health and readiness probes to flagd to monitor the state of the services.
- [x] Update the OpenFeature Operator to automatically configure the health and readiness checks.
- [x] Document the new behavior and configuration options in the OFO documentation.

## Resources

- https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/

**Comment by thisthat** [comment]
I had a look into this topic. We can re-use the HTTP server created for serving Prom metrics for the probes. This simplifies the implementation. Mind that K8s has a basic behavior regarding health probes: when it fails, it restarts the POD. Hence, we should not add any fancy configuration for this.
For the ready probe, I propose splitting the current `ISync` interface into two functions: `Init(Context)` and `Sync(Context, chan)`. This would also make a cleaner implementation for providers such as [gRPC](https://github.com/open-feature/flagd/blob/main/pkg/sync/grpc/grpc_sync.go).
