### ISSUE TITLE
[DOC] How to use Prometheus with Flagd

### ISSUE THREAD

**Issue by beeme1mr** [open-feature/flagd#422]
### Change in the documentation

Add documentation that explains how use Prometheus with Flagd. The docs should include information like how to scrape the metrics (e.g. what port is exposed by default) and what metrics are collected.

### Resources

- https://github.com/jupyterhub/jupyterhub/pull/2891/files

**Comment by Kavindu-Dodan** [comment]
This is done with latest telemetry improvements & updated documentation is available for flagd [1]. 

@beeme1mr  can you verify and close the issue ?  

[1] - https://github.com/open-feature/flagd/blob/main/docs/configuration/flagd_telemetry.md
