### ISSUE TITLE
[CI] Run disabled test suites (caching) with a long timeout on release PRs

### ISSUE THREAD

**Issue by skyerus** [open-feature/flagd#470]
### Requirements

The caching test suite was recently disabled due to slow file I/O in github actions. This has already caused [a caching bug](https://github.com/open-feature/go-sdk-contrib/pull/131) to slip by unnoticed.

We should consider running the suite in CI with a longer timeout on release PRs (on all PRs is imo unnecessarily tedious).

**Comment by skyerus** [comment]
Extending the sleep to 2 minutes still causes [unexpected behaviour](https://github.com/skyerus/flagd/actions/runs/4373408997/jobs/7651548503) in some instances (and eventual timeout of the entire test suite). This suggests that there may be something more to this than slow file I/O in github actions.
As it's not possible to reproduce locally and I've already sunk a considerable amount of time in this I'm going to put it on hold, leaving the caching tests disabled.

**Comment by beeme1mr** [comment]
No longer required due to changes in the testing harness.
