### ISSUE TITLE
[DOC] Document nuances of file-sync due to fs-notify and fs intricacies

### ISSUE THREAD

**Issue by toddbaert** [open-feature/flagd#479]
Things like [this](https://github.com/open-feature/flagd/blob/main/core/pkg/sync/file/filepath_sync.go), and the fact that users will see multiple events when files are modified with editors are somewhat surprising. Though they all "make sense", understanding how file-systems and most programs that modify files work, it can be confounding.

Let's add a section documenting some of these intricacies.

**Comment by agardnerIT** [comment]
I believe the link about should be: https://github.com/open-feature/flagd/blob/main/core/pkg/sync/file/filepath_sync.go

**Comment by beeme1mr** [comment]
@toddbaert please add this to the troubleshooting section. It could also be briefly mentioned in the file sync section as @agardnerIT mentioned.

- https://flagd.dev/concepts/syncs/?h=filepath#filepath-sync
- https://flagd.dev/faq/
