### ISSUE TITLE
Metrics for the kube-flagd-proxy

### ISSUE THREAD

**Issue by toddbaert** [open-feature/flagd#482]
We need metrics for the kube-flagd-proxy. We should have a discussion on exactly what metrics will be important here.

Expected outcomes of this issue:

- agreement on relevant metrics
- OTel metrics endpoint exposing those metrics

Relates to: https://github.com/open-feature/open-feature-operator/issues/379

**Comment by Kavindu-Dodan** [comment]
@toddbaert  seems this is done for flagd-proxy [1] may be @james-milligan  can confirm

[1] - https://github.com/open-feature/flagd/blob/main/core/pkg/service/sync/server.go#L93
