### ISSUE TITLE
[DOC] Remove Snap references until automated publishing is configured

### ISSUE THREAD

**Issue by beeme1mr** [open-feature/flagd#489]
### Change in the documentation

The version on Snap is out of date and the upgrade process hasn't been automated. [An issue](https://github.com/open-feature/flagd/issues/242) has is available to automate the process. However, until that's done, all references should be removed from the docs to avoid confusion.

**Comment by AlexsJones** [comment]
Or we could automate the release process!

**Comment by beeme1mr** [comment]
That would be great. Could you either invite me as a publisher to the existing snap account or add a publishing secret to the repo?
