### ISSUE TITLE
Refactor documentation to work with Docusaurus

### ISSUE THREAD

**Issue by beeme1mr** [open-feature/flagd#497]
## Overview

The current documentation consists of markdown files in GitHub. While this does work, it's a poor user experience. This issue is to refactor the documentation to work with Docusaurus, so it can be included in the OpenFeature docs as a subsection. The goal is to provide a user-friendly and organized documentation site that includes all the core OpenFeature projects.

## Requirements

- [ ] Refactor the current documentation to work with Docusaurus
- [ ] Create an organized and user-friendly documentation site
- [ ] Extend the documentation to answer the following questions:
	- [ ] What's flagd?
	- [ ] What problem does it solve?
	- [ ] What's an evaluation engine?
	- [ ] How does it relate to OpenFeature?
- [ ] Ensure that the documentation is easy to maintain and update

## Resources

Docusaurus documentation: https://docusaurus.io/docs/
Docusaurus GitHub repository: https://github.com/facebook/docusaurus
Current documentation: https://github.com/open-feature/flagd/tree/main/docs

**Comment by agardnerIT** [comment]
- [What is flagd?](https://github.com/open-feature/flagd/issues/505) will be resolved in this issue.
- [What problem does flagd solve?](https://github.com/open-feature/flagd/issues/506) will be resolved in this issue.
- [What is an evaluation engine?](https://github.com/open-feature/flagd/issues/507)
- [How does flagd relate to OpenFeature?](https://github.com/open-feature/flagd/issues/508)

**Comment by beeme1mr** [comment]
Resolved by: https://github.com/open-feature/flagd/pull/782
