### ISSUE TITLE
[BUG] Home Shortcut ~ not supported

### ISSUE THREAD

**Issue by agardnerIT** [open-feature/flagd#510]
### Observed behavior

`flagd start --port 8013 --uri=/root/flag.json` works perfectly.

`flagd start --port 8013 --uri=~/flag.json` results in:

```

                 ______   __       ________   _______    ______      
                /_____/\ /_/\     /_______/\ /______/\  /_____/\     
                \::::_\/_\:\ \    \::: _  \ \\::::__\/__\:::_ \ \    
                 \:\/___/\\:\ \    \::(_)  \ \\:\ /____/\\:\ \ \ \   
                  \:::._\/ \:\ \____\:: __  \ \\:\\_  _\/ \:\ \ \ \  
                   \:\ \    \:\/___/\\:.\ \  \ \\:\_\ \ \  \:\/.:| | 
                    \_\/     \_____\/ \__\/\__\/ \_____\/   \____/_/ 

2023-03-15T01:29:12.894Z        info    cmd/start.go:98 flagd version: 0.4.0 (408bb7c6420678706854932df3144253ada89f82), built at: 2023-03-02T19:53:06Z {"component": "start"}
2023-03-15T01:29:12.895Z        info    file/filepath_sync.go:40        Starting filepath sync notifier {"component": "sync", "sync": "filepath"}
2023-03-15T01:29:12.895Z        fatal   cmd/start.go:126        no such file or directory       {"component": "start"}
github.com/open-feature/flagd/cmd.glob..func1
        /home/runner/work/flagd/flagd/cmd/start.go:126
github.com/spf13/cobra.(*Command).execute
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:920
github.com/spf13/cobra.(*Command).ExecuteC
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:1044
github.com/spf13/cobra.(*Command).Execute
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:968
github.com/open-feature/flagd/cmd.Execute
        /home/runner/work/flagd/flagd/cmd/root.go:37
main.main
        /home/runner/work/flagd/flagd/main.go:30
runtime.main
        /opt/hostedtoolcache/go/1.19.3/x64/src/runtime/proc.go:250
```

### Expected Behavior

Both the "real" path and hte common shortcut `~` should work the same way.

**Comment by beeme1mr** [comment]
hey @agardnerIT, thanks for reporting this. I was able to reproduce this behavior. I think it could be a good first issue for someone. I'll add the label and see if there's interest.

**Comment by Kavindu-Dodan** [comment]
While agreeing with what @toddbaert mentioned. Seems you have an outdated flagd binary. The latest flagd versions expect flagd sources to have an appropriate prefix. For example, file sources require `file:` prefix. You can read more here [1].

And in my view, even with correct prefixes, handling this internally is not recommended as specific notations like `~` is complex to interpret based on the OS 

[1] - https://github.com/open-feature/flagd/blob/main/docs/configuration/configuration.md#uri-patterns

**Comment by AlexsJones** [comment]
It's an expansion and shouldn't be relied on as its not portable

**Comment by agardnerIT** [comment]
Thanks all. After reading the comments plus some background, I'm going to close this as "will not do". I don't think the benefits outweigh the issues we'd have trying to implement and maintain.
