### ISSUE TITLE
[REFACTOR] consolidate service configuration objects

### ISSUE THREAD

**Issue by james-milligan** [open-feature/flagd#524]
### Requirements

Currently the flagd `ConnectServer` handles 2 separate configuration objects:
[Configuration](https://github.com/open-feature/flagd/blob/c11ca7e189e827e5a38ca492851e201d54f5ae5e/core/pkg/service/iservice.go#L24)
```
type Configuration struct {
	ReadinessProbe ReadinessProbe
}
```
and
[ConnectServiceConfiguration](https://github.com/open-feature/flagd/blob/c11ca7e189e827e5a38ca492851e201d54f5ae5e/core/pkg/service/connect_service.go#L38)
```

type ConnectServiceConfiguration struct {
	Port             int32
	MetricsPort      int32
	ServerCertPath   string
	ServerKeyPath    string
	ServerSocketPath string
	CORS             []string
}
```

These should be consolidated into a single configuration object, and passed / set to the ConnectService in a. single action.
Currently `ConnectServiceConfiguration` is set on struct instantiation, with `Configuration` being passed in the [`Serve`](https://github.com/open-feature/flagd/blob/c11ca7e189e827e5a38ca492851e201d54f5ae5e/core/pkg/service/iservice.go#L32) method:
```
Serve(ctx context.Context, eval eval.IEvaluator, svcConf Configuration) error
```

IMO the `ConnectServiceConfiguration ` object should be merged into `Configuration` and passed to flagd via the Serve method, as this gives a cleaner interface + standardised type across future services

**Comment by odubajDT** [comment]
Hey, I would like to pick this issue
