### ISSUE TITLE
[BUG] Fallback to default port if FLAGD_PORT isn't valid

### ISSUE THREAD

**Issue by skyerus** [open-feature/flagd#580]
### Observed behavior

[This issue](https://github.com/open-feature/open-feature-operator/issues/431) led to the discovery that flagd parses non integer values as 0.

### Expected Behavior

Fallback to flagd's default port if FLAGD_PORT is invalid i.e. non-integer

**Comment by bacherfl** [comment]
@skyerus  @toddbaert I'd like to work on a fix for this

**Comment by toddbaert** [comment]
> @skyerus @toddbaert I'd like to work on a fix for this

assigned!
