### ISSUE TITLE
Licence compliance (automated if possible)

### ISSUE THREAD

**Issue by toddbaert** [open-feature/flagd#581]
Fossa has identified [license issues](https://app.fossa.com/projects/git%2Bgithub.com%2Fopen-feature%2Fflagd/refs/branch/main/898a820f46801363bc2e16eb0a69ea3c2a8d80de/issues/licensing?page=1&count=20&sort=created_at_desc&status=active&revisionScanId=38198388) with flagd. The only requirement I can see is a requirement to include licenses.

Most are Mozilla. We need to add declarations for these. It seems like we may be able to automate this using: https://github.com/google/go-licenses

DoD: 

- 3rd party licenses collection published/exposed with builds

OR

- determination this is not possible or necessary

**Comment by Kavindu-Dodan** [comment]
I checked running the tool and we only have a few types of licenses (Apache, BSD 2,3 & MIT). And we must include them in the source with some mechanism if we need to comply with their clause (see example at chrome://credits/)

To get started, we can expose CSV which we can attach as a release artifact of flagd & flagd proxy (main deliverables).

**Comment by toddbaert** [comment]
> I checked running the tool and we only have a few types of licenses (Apache, BSD 2,3 & MIT). And we must include them in the source with some mechanism if we need to comply with their clause (see example at chrome://credits/)

Yep, I think that's really the only thing we need to do to fix the compliance issue, then I can check off all the dependencies with such requirements in FOSSA.

> To get started, we can expose CSV which we can attach as a release artifact of flagd & flagd proxy (main deliverables).

That sounds good to me. The way OTel generally seems to do this is with a single appended file (can't seem to find it now) but I'm OK with whatever is the easiest to automate.

**Comment by Kavindu-Dodan** [comment]
I will give this a go and see if I can get the release assets :)

**Comment by Kavindu-Dodan** [comment]
Managed to get a working setup in a test repo 

Code - https://github.com/Kavindu-Dodan/flag-test-ground/blob/main/.github/workflows/run-release.yaml#L74-L89
Artefacts - https://github.com/Kavindu-Dodan/flag-test-ground/releases/tag/v0.1.1 (see license.tar.gz)

Will add this to flagd build

**Comment by toddbaert** [comment]
> Managed to get a working setup in a test repo
> 
> Code - https://github.com/Kavindu-Dodan/flag-test-ground/blob/main/.github/workflows/run-release.yaml#L74-L89 Artefacts - https://github.com/Kavindu-Dodan/flag-test-ground/releases/tag/v0.1.1 (see license.tar.gz)
> 
> Will add this to flagd build

I wasn't able to see the licence collection there, but I can see it here: https://github.com/Kavindu-Dodan/flag-test-ground/releases/tag/v0.1.6

This is great! If possible, I think it would be great to name it `third_party_licenses.zip` or something like that.

**Comment by Kavindu-Dodan** [comment]
@toddbaert  sorry 😿 ,  I did some cleanup as I was testing a few improvements. You can find the latest build here [1]

Regarding naming, for flagd we have two build steps - **flagd** & **flagd-proxy**. We can name each artifact like `flagd-licenses.zip` & `flagd-proxy-licenses.zip`

Also, I am thinking of appending the license error txt for each artifact (see [2]) so that we can refer to errors if any. 

[1] - https://github.com/Kavindu-Dodan/flag-test-ground/releases/tag/v0.1.7
[2] - [licenseErrors.txt](https://github.com/Kavindu-Dodan/flag-test-ground/releases/download/v0.1.7/licenseErrors.txt)

**Comment by toddbaert** [comment]
> Regarding naming, for flagd we have two build steps - flagd & flagd-proxy. We can name each artifact like flagd-licenses.zip & flagd-proxy-licenses.zip

That's good, but I think we should make it clear these are third party licenses in the name as well. I don't want people to be confused and think _our_ actual license is something other than Apache.
