### ISSUE TITLE
[Feature] [Question] GRPC service

### ISSUE THREAD

**Issue by AlexsJones** [open-feature/flagd#6]
In order to support more protocols, GRPC seems like a sensible schema to support.
This does also mean that we will need to be opinionated on the interfaces that the client side will need to consume and also think about where the proto files will live in terms of the repository as this has dependency implications.

**Comment by beeme1mr** [comment]
I think this interface would just need to comply with the provider spec. Using gRPC should make creating a flagd provider in various languages fairly straightforward.
