### ISSUE TITLE
[BUG] file path sync is not working in windows

### ISSUE THREAD

**Issue by Kavindu-Dodan** [open-feature/flagd#630]
### Observed behavior

A community user reached and noted that file path sync is not working for flagd when used in Windows OS.  According to the explanation, flag definitions were not updated when the flag source file is changed.

### Expected Behavior

flag definitions must get updated correctly from file source

**Comment by toddbaert** [comment]
[fsnotify](https://github.com/fsnotify/fsnotify) is supposed to support windows, but I've had trouble getting it working, as has @heckelmann .

Each OS uses a different underlying mechanism for seeing fs changes, so the behaviors might not be exactly the same.

**Comment by Kavindu-Dodan** [comment]
Thank you @toddbaert  

@RealAnna  will investigate further on this and let's try to fix OR document this behavior for Windows

**Comment by RealAnna** [comment]
Tested by building main directly on windows 11. 
The only issue I had was I needed to allow networking when the windows defender popped up. After that, I could run flagd on a command prompt and modify the file. A few seconds are needed for the update of the flag to be visible.

The curl command in the README only works within bash, since windows curl has a different syntax.

![image](https://user-images.githubusercontent.com/89971034/234795295-53e747dd-c9d0-45ea-ba85-0560639e3a72.png)

```
$ curl -X POST "localhost:8013/schema.v1.Service/ResolveString" -d '{"flagKey":"myStringFlag","context":{}}' -H "Content-Type: application/json"
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    93  100    54  100    39  42959  31026 --:--:-- --:--:-- --:--:-- 
93000{"value":"val12", "reason":"STATIC", "variant":"key1"}

 ~
$ curl -X POST "localhost:8013/schema.v1.Service/ResolveString" -d '{"flagKey":"myStringFlag","context":{}}' -H "Content-Type: application/json"
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    95  100    56  100    39  28169  19617 --:--:-- --:--:-- --:--:-- 
95000{"value":"val1333", "reason":"STATIC", "variant":"key1"}
```

**Comment by beeme1mr** [comment]
@Kavindu-Dodan can we close this issue now that a workaround is documented?

**Comment by Kavindu-Dodan** [comment]
@beeme1mr  yes, this can be closed. We have good documentation to cover requirements to run flagd in Windows.
