### ISSUE TITLE
[FEATURE] Ignore DISABLED flags from storage layer

### ISSUE THREAD

**Issue by Kavindu-Dodan** [open-feature/flagd#673]
### Requirements

**Background**

According to configuration guideline, when a flag is disabled, it is considered as if it doesn't exisit [1]

> When the state is set to "DISABLED", flagd will behave like the flag doesn't exist.

However, in the flagd implementation, we still handle Disabled flags and return errors to evaluation requests.

**Desired behavior**

PR https://github.com/open-feature/flagd/pull/670 & https://github.com/open-feature/flagd/pull/672 improved error handling and introduced bug fixes to disabled flags. Going forward, disabled flags must be ignored from storage which will result in flag not found status matching the configuration guide stated above

[1] - https://github.com/open-feature/flagd/blob/9490ed62e2fc589af8ae7ee26bfd559797a1f83c/docs/configuration/flag_configuration.md?plain=1#L14

**Comment by thisthat** [comment]
I would not ignore them entirely, but print an "info" or "warning" log message to notify somehow that a flag is disabled.

**Comment by toddbaert** [comment]
> I would not ignore them entirely, but print an "info" or "warning" log message to notify somehow that a flag is disabled.

Ya we could do this when we update the flag state and persist it, or we could keep them in a disabled state and mention it there (though that might add a lot of log-noise)

**Comment by Kavindu-Dodan** [comment]
Listing down the pros & cons of proposals 

**Ignore at storage**

Pros - Fewer flags in cache (storage), considering that there can be several Disabled flags.  And no extra logic for filtering
Cons - If we need a debug log at evaluation time for disabled flags, then we can't do that as we do not have data of disabled flags 

**Filter at retrieval**

Pros - Can provide logs at evaluation time for visibility. Potential future changes (if any) for Disabled flags
Cons - Filtering/check for state is a cost. Storage (cache) must be fast and must contain minimal logic
