### ISSUE TITLE
Unix socket support

### ISSUE THREAD

**Issue by beeme1mr** [open-feature/flagd#74]
## Overview

In some situations (i.e. Kubernetes pod) it would be useful to communicate over a Unix socket instead of a TCP.

## Requirements

- [ ] Configurable via an argument
- [ ] TCP is used by default but can be disabled
- [ ] Socket is properly closed when FlagD is stopped

**Comment by AlexsJones** [comment]
I'd like to discuss this more before anyone starts work on it

**Comment by beeme1mr** [comment]
@AlexsJones, are you okay with me closing this issue? If so, I'll create a follow up issue to remove the socketpath arg.

**Comment by AlexsJones** [comment]
I think we should implement this, but I think it needs an OFEP first, so okay!

**Comment by beeme1mr** [comment]
Closing until an OFEP has been accepted.
