### ISSUE TITLE
[DOC] sem_ver docs contains starts_with info

### ISSUE THREAD

**Issue by agardnerIT** [open-feature/flagd#762]
### Change in the documentation

https://github.com/open-feature/flagd/blob/main/docs/configuration/sem_ver_evaluation.md contains information about `starts_with` but the correct place for that is https://github.com/open-feature/flagd/blob/main/docs/configuration/string_comparison_evaluation.md

Solution: Just remove the `starts_with` content from https://github.com/open-feature/flagd/blob/main/docs/configuration/sem_ver_evaluation.md

This should be marked as a "good first issue"

**Comment by beeme1mr** [comment]
Fixed: https://github.com/open-feature/flagd/commit/b99b5dac9167e2f41e53c414fb9b165e0bc0cd37
