### ISSUE TITLE
[BUG] flagd version incorrect for 0.6.0

### ISSUE THREAD

**Issue by agardnerIT** [open-feature/flagd#764]
### Observed behavior

1. Download the `0.6.0` version of `flagd`
2. Extract and run `flagd_linux_x86_64 version` which shows:

```
$ ./flagd_linux_x86_64  version

                 ______   __       ________   _______    ______
                /_____/\ /_/\     /_______/\ /______/\  /_____/\
                \::::_\/_\:\ \    \::: _  \ \\::::__\/__\:::_ \ \
                 \:\/___/\\:\ \    \::(_)  \ \\:\ /____/\\:\ \ \ \
                  \:::._\/ \:\ \____\:: __  \ \\:\\_  _\/ \:\ \ \ \
                   \:\ \    \:\/___/\\:.\ \  \ \\:\_\ \ \  \:\/.:| |
                    \_\/     \_____\/ \__\/\__\/ \_____\/   \____/_/

flagd: dev (HEAD), built at: unknown
```

### Expected Behavior

`flagd version` should show `0.6.0`

**Comment by thisthat** [comment]
The images pushed to registries are correctly built and have all metadata info filled in. Images built and attached to the release do not propagate the info about version etc to the go build cmd: https://github.com/open-feature/flagd/blob/main/.github/workflows/release-please.yaml#L182

**Comment by beeme1mr** [comment]
We're explicitly setting version, commit, and date as build args when [creating the image](https://github.com/open-feature/flagd/blob/main/.github/workflows/release-please.yaml#L118-L120). This isn't being done when creating the individual binaries. However, the version is set as an environment variable [here](https://github.com/open-feature/flagd/blob/main/.github/workflows/release-please.yaml#L161). I'm a bit surprised that the version isn't working, but it would probably be better to explicitly set the build arg anyways.
