### ISSUE TITLE
Define community structure

### ISSUE THREAD

**Issue by agardnerIT** [open-feature/flagd#803]
How do I become a flagd:

1. Member
2. Promoter
3. Contributor
4. Maintainer
5. Docs maintainer

What even are the "levels" and how do I "move through" them, when, why and how?

For example, I would like to put myself forward as a docs maintainer.

@staceypotter FYI

**Comment by beeme1mr** [comment]
The community structure should come from the OpenFeature org guidelines.

https://openfeature.dev/community/
