### ISSUE TITLE
[DOC] Point from /docs/other_resources/systemd_service.md to website

### ISSUE THREAD

**Issue by agardnerIT** [open-feature/flagd#811]
### Change in the documentation

Reword this page https://github.com/open-feature/flagd/blob/main/docs/other_resources/systemd_service.md to instead point to https://flagd.dev/nonk8s/systemservice/

**Comment by agardnerIT** [comment]
Will be closed by #825

**Comment by beeme1mr** [comment]
https://flagd.dev/deployment/#systemd
