### ISSUE TITLE
Invalid Default Variant

### ISSUE THREAD

**Issue by beeme1mr** [open-feature/flagd#83]
## Overview

A flag configuration with an invalidate default variant returns the error code `TYPE_MISMATCH`.

## Steps to reproduce

1. Start flagd `./flagd start -f config/samples/example_flags.json --service-provider http --sync-provider filepath`
2. Change the `defaultVariant` to `other`.
3. cURL flagd `curl -X POST "localhost:8080/flags/myBoolFlag/resolve/boolean"`

## Expectation

Invalid default variants should be caught during configuration validation.

**Comment by skyerus** [comment]
https://github.com/open-feature/flagd/pull/88
