### ISSUE TITLE
[FEATURE] gRPC Health Check must be implemented in case flagd is accessed via AWS ALB

### ISSUE THREAD

**Issue by kworkbee** [open-feature/flagd#831]
### Requirements

To configure flagd to be accessed via AWS ALB when deployed as standalone rather than as OpenFeature Operator, it must be specified the health check related properties of ALB, which must be implemented as '/AWS.ALB/healthcheck' path in flagd.

**Comment by toddbaert** [comment]
@Kavindu-Dodan @bacherfl @thisthat is this as simple as making `healthz/readyz` configurable?

**Comment by Kavindu-Dodan** [comment]
@kinyoklion  I don't fully understand your requirement.

Regardless of the application you are deploying (here you are referencing to flagd), AWS allows your to configure health check endpoint of your ALB.

Please check these steps to configure this [^1] in your EC2 instance.

flagd expose readiness & liveness probes as described in our documentation [^2]. So you can configure health check endpoints for them. 

[^1]: https://docs.aws.amazon.com/elasticloadbalancing/latest/application/target-group-health-checks.html#modify-health-check-settings
[^2]: https://github.com/open-feature/flagd/blob/main/web-docs/concepts/architecture.md#readiness--liveness-probes

**Comment by toddbaert** [comment]
I think you at-ed @kinyoklion when you meant to at @kworkbee

**Comment by Kavindu-Dodan** [comment]
> @Kavindu-Dodan I think you at-ed @kinyoklion when you meant to at @kworkbee 😅

yeah, my bad 😞 . updated the comment :D

**Comment by kworkbee** [comment]
@toddbaert @Kavindu-Dodan Hello, Thanks for your answer.

I tried it, but due to AWS ALB Ingress Controller setting, if backend protocol version uses gRPC, it seems that only gRPC is available as healthcheck. You can specify the (Not HTTP) Status Code only as the status code of the gRPC.

**Comment by beeme1mr** [comment]
@Kavindu-Dodan, would it be possible to add support for gRPC-based health checks in addition to HTTP?

**Comment by toddbaert** [comment]
I can look into this. It seems that we do indeed need a gRPC healthcheck that returns a value between 0-99 (probably 12) in order to satisfy AWS' requirements.

**Comment by toddbaert** [comment]
I think this is a legimitate issue and we should fix it by adding a standard gRPC health endpoint, which conforms to [this standard proto](https://github.com/grpc/grpc/blob/master/src/proto/grpc/health/v1/health.proto).

**Comment by toddbaert** [comment]
@kworkbee I've opened [PR](https://github.com/open-feature/flagd/pull/861) to fix this. According to what I see in the answer for AWS [here](https://repost.aws/questions/QUA9UNY0sgSaSN7ZQ6A4u3eQ/grpc-api-through-aws-alb#ANWmBAXTqlTzaIFoKKrS3k2Q), they should support the standard gRPC health check (/grpc.health.v1.Health/Check), which is what I've implemented. Note, we are returning code 0 (success) on the health check.

**Comment by toddbaert** [comment]
@kworkbee this has been released https://github.com/open-feature/flagd/pkgs/container/flagd

According to my research this should work with the AWS infra, since it's a standard gRPC healthcheck. I tested it manually with the standard proto and it worked, but I never actually tested it in AWS. Let us know if this helps you.

**Comment by kworkbee** [comment]
@toddbaert, I tested with a new release and found that it works! Thanks for your support.
