### ISSUE TITLE
Review PR Actions and optimise

### ISSUE THREAD

**Issue by agardnerIT** [open-feature/flagd#835]
The checks being executed in the PR are numerous and an analysis during this PR has shown that many contain duplicated logic.

This leads to two outcomes:

1. Unhappy contributors: They're waiting for slow, duplicated or irrelevant things to happen. For example:
   - 4x environment rebuilds during a the same PR
   - Code and binaries being built, security scanned and tested during PRs that only touch markdown files.
3. Increased costs: More GitHub Actions executing means more CPU time spent and this more resources consumed. This has two impacts:
   - Resource usage
   - Environmental impact

This issue is to review and re-work the GitHub actions to ensure they're lean and minimal for whatever task they're running-for. For example, documentation PRs should not have tasks related to code rebuilds and tests as, by definition, the code hasn't changed and is thus irrelevant.

**Comment by agardnerIT** [comment]
See the irrelevant codecov report on https://github.com/open-feature/flagd/pull/838

I change two files - both markdown docs files - and codecov is complaining (and giving a red check mark) but that check is entirely irrelevant.

**Comment by beeme1mr** [comment]
This happened because you change the mkdoc.yml file which isn't currently excluded from the build action. Codecov then compares your outdated branch to what's in main. Updating the branch resolved the issue.

**Comment by beeme1mr** [comment]
Resolved by: https://github.com/open-feature/flagd/blob/main/.github/workflows/build.yaml#L3-L16
