### ISSUE TITLE
Document Targeting Rules

### ISSUE THREAD

**Issue by beeme1mr** [open-feature/flagd#84]
Add documentation on how a targeting rule can be defined using JSON Logic.

**Comment by skyerus** [comment]
Should this be added to the README?

**Comment by toddbaert** [comment]
> Should this be added to the README?

I think so. Probably with a link to https://jsonlogic.com/ and https://jsonlogic.com/play.html

**Comment by beeme1mr** [comment]
You could add it to the main README or create a docs folder with a dedicated targeting doc.

**Comment by toddbaert** [comment]
> You could add it to the main README or create a docs folder with a dedicated targeting doc.

@beeme1mr that would only apply to flagd though, right? We wouldn't want to document targeting for all vendors, I think... which brings us back to the question about adding flagd doc to the docsite.

**Comment by beeme1mr** [comment]
This should be focused on FlagD targeting rules only.

**Comment by skyerus** [comment]
https://github.com/open-feature/flagd/pull/93
