### ISSUE TITLE
Rename "metrics" port to "management" port

### ISSUE THREAD

**Issue by toddbaert** [open-feature/flagd#867]
Currently, the "metrics" port configuration controls the port the HTTP readyz/healthz checks, gRPC health check, and metrics.

We should change the name to "management" port to make clear it exposes more than just metrics.

Relates to: https://github.com/open-feature/flagd/pull/863

Be sure to update any related doc.

**Comment by Saurabhkr952** [comment]
I'd like to work on this. Changing "metrics" to "management" port makes sense given its broader functionality. I'm ready to implement the change and update the docs. 
Please guide me on the next steps or any specific requirements for this contribution.

Thank you!

**Comment by toddbaert** [comment]
Thanks @Saurabhkr952 . Once https://github.com/open-feature/flagd/pull/863 is merged, I think it should be a matter of:

- updating the viper config (use `managementPort` and fallback to `metricsPort` if `managementPort` is not defined), and add some kind of deprecation warning if possible
- update all mention of `metrics port / metricsPort / etc` in docs, and mention the deprecation above
- update code / config objects to use `managementPort` instead of `metricsPort`

I think that'll about cover it.

**Comment by agardnerIT** [comment]
Please also document this as a new page on the website (in `/web-docs`) as a Definition of done - so that this doesn't go out without documentation.

Saying that, I don't think we have documentation on this piece yet at all...

**Comment by craigpastro** [comment]
It seems that work on the issue has gotten a bit stale. Does anyone mind if I pick this task up? @Saurabhkr952?

**Comment by beeme1mr** [comment]
Hey @craigpastro, that would be great! I've reassigned the issue to you. Thank you 🙇

**Comment by craigpastro** [comment]
Thanks @beeme1mr! I'll try to get to it soon.
