### ISSUE TITLE
Deprecate "fractionalEvaluation", rename to "fractional".

### ISSUE THREAD

**Issue by toddbaert** [open-feature/flagd#871]
With the completion of https://github.com/open-feature/flagd/issues/843 we have a much more powerful `fractionalEvaluation`.

One problem remains:

```
"fractionalEvaluation": [
          "email"
          [
            "red",
            25
          ],
          [
            "blue",
            25
          ],
          [
            "green",
            25
          ],
          [
            "purple",
            25
          ]
        ]
```
has been replaced with:

```
"fractionalEvaluation": [
          {
            "var": "email"
          },
          [
            "red",
            25
          ],
          [
            "blue",
            25
          ],
          [
            "green",
            25
          ],
          [
            "purple",
            25
          ]
        ]
```

However, there's a problem which was not immediately apparent. "email" in the first variant is treated as a literal in our new operator: by the time our operator runs, it's difficult (impossible?) to know if the first value ("email" in this case) was the result of an expression ( "var": "myProp" ) or it was hard-coded. This means we _should_ deprecate the old `fractionalEvaluation` and ignore it, and instruct people on how to properly use a new operator `fractional`. We can do this with a helpful log warning.

EDIT:

I've maintained the old behavior of`fractionalEvaluation`, and added a deprecation log warning, and moved the new implementation to `fractional`.

The deprecation warning log message points _directly_ to the migration instructions in the web-docs.

**Comment by Kavindu-Dodan** [comment]
> by the time our operator runs, it's difficult (impossible?) to know if the first value ("email" in this case) was the result of an expression ( "var": "myProp" ) or it was hard-coded

A hack is to check if the first value (reference key) is present in the `data`. If it does, we can safely _assume_ it is a replacement performed by Json logic for a variable. If not, then we can assume it's a user inserted literal that requires a replacement (similar to first example). Then we attempt to fill that from data as a fallback.

**Comment by toddbaert** [comment]
> > by the time our operator runs, it's difficult (impossible?) to know if the first value ("email" in this case) was the result of an expression ( "var": "myProp" ) or it was hard-coded
> 
> A hack is to check if the first value (reference key) is present in the `data`. If it does, we can safely _assume_ it is a replacement performed by Json logic for a variable. If not, then we can assume it's a user inserted literal that requires a replacement (similar to first example). Then we attempt to fill that from data as a fallback.

Ya, that's possible, but it does feel hacky. We'd have to implement it elsewhere too.

What we've implemented here feels "right" to me... Using "var" to reference data... That's consistent with all other json logic. TBH we probably never should have just taken a string as the first arg. Hindsight is 20/20 though.

I plan on doing a `git mv` on what was just implemented by @craigpastro to a new evaluator called "fractional" and then just replacing the contents of the old evaluator with a depreciation warning. We can even link a little migration guide in the docs which will amount to telling people to do `{"var": "xyz"}` where they had `"xyz"`

**Comment by toddbaert** [comment]
https://github.com/open-feature/flagd/pull/873 fixes this in a non-breaking way.

**Comment by agardnerIT** [comment]
From the description above, I don't understand how changing the word `fractionalEvaluation` to `fractional` fixes anything?
This sounds like a problem in the "new operator", not the wording used to describe the act of doing a `fractional evaluation`.

FWIW `fractionalEvaluation` is a lot more descriptive that `fractional`.
