### ISSUE TITLE
[DOC] Migrate CONTRIBUTING.md to website

### ISSUE THREAD

**Issue by agardnerIT** [open-feature/flagd#874]
### Change in the documentation

Move https://github.com/open-feature/flagd/blob/main/CONTRIBUTING.md to the website

**Comment by agardnerIT** [comment]
Closed the above PR, this will be closed by #825

**Comment by beeme1mr** [comment]
The contributing doc should remain in the repo. It has special meaning in GitHub and would be where contributors would look.
