### ISSUE TITLE
[DOC] Add a "get started with flagd one-liner"

### ISSUE THREAD

**Issue by agardnerIT** [open-feature/flagd#895]
### Change in the documentation

Very prominently (top of homepage?) we should add a very short copy / paste snippet on how to get started with flagd.

Probably using the `docker run` command from [here](https://flagd.dev/nonk8s/#flagd-start).

Perhaps this should be a terminal recording?

```
docker run \
    --rm -d \
    --name flagd \
    -p 8013:8013 \
    ghcr.io/open-feature/flagd:latest start \
    --uri https://raw.githubusercontent.com/open-feature/flagd/main/samples/example_flags.flagd.json

curl http://localhost:8013/schema.v1.Service/ResolveString -H "Content-Type: application/json" -d '{"flagKey": "myStringFlag"}'
```

**Comment by beeme1mr** [comment]
https://flagd.dev/quick-start/
