### ISSUE TITLE
Intermittent Performance Issues

### ISSUE THREAD

**Issue by beeme1mr** [open-feature/flagd#9]
The Flagd process hangs intermittently for many seconds after multiple HTTP requests are made.

**Comment by AlexsJones** [comment]
This is likely due to the channel buffer not draining correctly through a select, I'll check it out

**Comment by AlexsJones** [comment]
```
	go server.Serve(

		func(ir service.IServiceRequest) service.IServiceResponse {

			if ir.GetRequestType() == service.SERVICE_REQUEST_ALL_FLAGS {
				return ir.GenerateServiceResponse(<-messageBuffer)
			}
			return nil
		})

	for {
		data, err := syncr.Fetch()
		if err != nil {
			log.Warn(err.Error())
		}
		messageBuffer <- data
		time.Sleep(time.Second * 10)
	}
```

The current loop will force a wait for 10 seconds before a sync Fetch and subsequent channel message update - will fix this.

**Comment by AlexsJones** [comment]
https://github.com/open-feature/flagd/pull/10

Fixed here, we will need to improve this later because each request hitting a direct call is not performant, I think a simple cache would be a better long term option
