### ISSUE TITLE
[FEATURE] Reusable Targeting Operations

### ISSUE THREAD

**Issue by beeme1mr** [open-feature/flagd#96]
## Overview

Targeting rules in flagD allow users to define arbitrarily complex rulesets using JSON logic. However, this flexibility introduces administrative challenges when managing a large number of flags. Reusable targeting operations would allow common targeting rules to be shared between many flags.

The following is an example of a configuration that has multiple flags that use a similar rule.

<details>
  <summary>Current flag configurations</summary>

```json
{
   "flags": {
        "hex-color": {
          "variants": {
            "red": "CC0000",
            "green": "00CC00",
            "blue": "0000CC",
            "yellow": "yellow"
          },
          "defaultVariant": "red",
          "state": "ENABLED",
          "targeting": {
            "if": [
              {
                "in": ["@faas.com", {
                  "var": ["email"]
                }]
              }, "green", null
            ]
          }
        },
        "fib-algo": {
          "variants": {
            "recursive": "recursive",
            "memo": "memo",
            "loop": "loop",
            "binet": "binet"
          },
          "defaultVariant": "recursive",
          "state": "ENABLED",
          "targeting": {
            "if": [
              {
                "in": ["@faas.com", {
                  "var": ["email"]
                }]
              }, "binet", null
            ]
          }
        }
    }
}
```
</details>

A shared operation would allow the core logic to be moved to a shared location and be referenced within a targeting rule.

<details>
  <summary>Proposed flag configurations</summary>

```json
{
   "flags": {
        "hex-color": {
          "variants": {
            "red": "CC0000",
            "green": "00CC00",
            "blue": "0000CC",
            "yellow": "yellow"
          },
          "defaultVariant": "red",
          "state": "ENABLED",
          "targeting": {
            "if": [
               {
                "sharedOperations":  "email-with-faas"
              }, "green", null
            ]
          }
        },
        "fib-algo": {
          "variants": {
            "recursive": "recursive",
            "memo": "memo",
            "loop": "loop",
            "binet": "binet"
          },
          "defaultVariant": "recursive",
          "state": "ENABLED",
          "targeting": {
            "if": [
              {
                "sharedOperations":  "email-with-faas"
              }, "binet", null
            ]
          }
        }
    }
    "sharedOperations": {
        "email-with-faas":  {
                "in": ["@faas.com", {
                  "var": ["email"]
                }]
              }
    }
}
```
</details>

### Requirements

- [x] Shared operations are defined in the schema
- [x] If there are collisions between shared operations, the priority goes to the later (e.g. example_operation < example_operation_secondary).
- [x] Targeting rules are compliant with the JSON Logic spec
- [x] An example config is added under `config/samples`
- [x] Readme includes an example configuration

### Questions

- Is `shared operations` a good property name? If not, what would be better?
- What's the expected behavior if a targeting rule contains an invalid shared operation?

### Resources

- [Custom Operations in JSON Logic](https://jsonlogic.com/add_operation.html)

**Comment by skyerus** [comment]
My naming preference is just `operations` as that's what `JSON Logic` have gone with

**Comment by skyerus** [comment]
[Solution](https://github.com/open-feature/flagd/pull/101):
- Introduce an `evaluators` key at the same level as `flags` in [the flag config json file](https://github.com/open-feature/flagd/pull/101/files#diff-e6b31651088c9f80b62f07cd167874b5208c3ea34d874a8967e87aedf77c5b6bR81).
- Add a [json logic operator](https://jsonlogic.com/add_operation.html) that takes a name as a parameter and looks up the json object under the `evaluators` object in the flag config json file. The found object is processed as json logic using the given data (this is effectively nested json logic). The result is passed back to the [caller of the evaluator](https://github.com/open-feature/flagd/pull/101/files#diff-e6b31651088c9f80b62f07cd167874b5208c3ea34d874a8967e87aedf77c5b6bR75).

The downside of this solution is that the json logic operator processes the evaluator logic and returns a string value to the caller. This is a problem as `"false" != false`.

Workarounds:
- Return strings that [json logic considers true/false in the right context](https://jsonlogic.com/truthy.html) e.g. [a non-empty string is true whereas an empty string is false](https://github.com/open-feature/flagd/pull/101/files#diff-e6b31651088c9f80b62f07cd167874b5208c3ea34d874a8967e87aedf77c5b6bR88).
- In the [json logic operator evaluator](https://github.com/open-feature/flagd/pull/101/files#diff-505066b25e2ff0ede87d3db99ecff5c3c620b03c1db23a46dafcf0ec4fd9a43aR176) check whether the resultant string is equal to `"true"` or `"false"` and return the boolean value.

Any preference or suggestions for other workarounds? @beeme1mr @james-milligan @toddbaert @AlexsJones

**Comment by toddbaert** [comment]
@skyerus @beeme1mr I really like this conceptually, but I _think_ perhaps it would be better to use JSON-schema's in-built $refs: http://json-schema.org/draft/2020-12/json-schema-core.html#ref if possible. Then we could have the JSON schema parser do the expansion for us before we evaluate the JSON logic, and the meaning would be immediately clear to anyone familiar with JSON schema.

I'm not sure, but I think this should work out-of-the-box with out jsonschema parser module: https://github.com/xeipuuv/gojsonschema

**Comment by skyerus** [comment]
> @skyerus @beeme1mr I really like this conceptually. I _think_ perhaps it would be a good idea to use something that looks more like JSON-schema's in-built $refs: http://json-schema.org/draft/2020-12/json-schema-core.html#ref , and use a special token to indicate this is a sort of "reference" object, ie: `$evaluator`.

Great suggestion, I've now implemented this. Let me know if it's not what you had in mind: https://github.com/open-feature/flagd/pull/101

**Comment by skyerus** [comment]
Closed with https://github.com/open-feature/flagd/pull/101
