### ISSUE TITLE
How should invalid configurations changes be handled?

### ISSUE THREAD

**Issue by beeme1mr** [open-feature/flagd#98]
## Summary

An invalid flag configuration during start up will result in no flags being loaded into flagD. There's also an error message that says "set state: invalid JSON file". However, if an invalid flag configuration is made after flagD initially loads, the previously valid flag value is retained. How should this be handled?

### Reproduce startup behavior

1. Change line 7 in the `example_flags.json` file to a string value
2. Run flagD `./flagd start -f config/samples/example_flags.json --service-provider http --sync-provider filepath`
3. cURL the flag `curl -X POST "localhost:8080/flags/myBoolFlag/resolve/boolean"`

You should see {"error_code":"FLAG_NOT_FOUND","reason":"ERROR"}

### Reproduce runtime behavior

1. Revert the `example_flags.json` file if you modified it above
2. Run flagD `./flagd start -f config/samples/example_flags.json --service-provider http --sync-provider filepath`
1. Change line 7 in the `example_flags.json` file to a string value
4. cURL the flag `curl -X POST "localhost:8080/flags/myBoolFlag/resolve/boolean"`

You should see {"value":true,"reason":"STATIC","variant":"on"}

**Comment by beeme1mr** [comment]
@AlexsJones @james-milligan @skyerus I would be interested your thoughts on this.

**Comment by skyerus** [comment]
It's worth noting that the runtime behaviour example logs an error after step 3:
```
{"component":"evaluator","evaluator":"json","level":"error","msg":"invalid JSON file","time":"2022-08-04T09:30:49+01:00"}
```
In my opinion this is enough, a flag modifier can check whether the new values they've provided are valid by checking the logs. I'd be interested to hear other opinions
