### ISSUE TITLE
[RESEARCH] Create devcontainer "Feature" for flagd 

### ISSUE THREAD

**Issue by agardnerIT** [open-feature/flagd#986]
### Requirements

It would be great to be able to include flagd in a devcontainer in a "one click" action. I believe (although I've done no more than cursory Googling) this can be done by [creating a custom devcontainer feature](https://code.visualstudio.com/blogs/2022/09/15/dev-container-features#_authoring).

Then anyone can easily check a box which effectively says "I need flagd available in this dev environment".

**Comment by beeme1mr** [comment]
This isn't something we're going to prioritize right now.
