### ISSUE TITLE
[FEATURE] Rich validation and IDE editor support via rigorous JSON validation

### ISSUE THREAD

**Issue by toddbaert** [open-feature/flagd#988]
### Requirements

Use a rigorous schema for validation in flagd. See [dependency issue](https://github.com/open-feature/flagd-schemas/issues/115) for full details.

**Comment by weyert** [comment]
How do you imagine the editor? A simple web gui to visually add feature flags or more to edit the JSON file? I think the former is a better user experience?

**Comment by toddbaert** [comment]
Rally the only thing I wanted to do was add a schema and publish it online. If you do that, most IDEs will add basic validation. See the screenshot in this PR: https://github.com/open-feature/flagd-schemas/pull/120

I've finished the schema with that PR, the only thing to do now is publish it to flagd.dev (that's what I'll use this issue for).

**Comment by austindrenski** [comment]
@beeme1mr @toddbaert what do you guys think about getting this added to the official JSON Schema Store?

Many IDEs pull schemas from there by default, and it would allow (depending on your IDE) schema recognition without having to include  `$schema` manually (e.g. this is the case for JetBrains tools).

I haven't gone through their contributor process before, but from a quick skim of their docs, it looks like they offer options to host in their repo _or_ externally _(don't think we'd need to, but just calling it out in case there are any concerns about needing to iterate faster than we think their process would allow)_:

- https://schemastore.org
- https://github.com/SchemaStore/schemastore/blob/master/CONTRIBUTING.md

**Comment by beeme1mr** [comment]
It's already there 😄 
https://github.com/SchemaStore/schemastore/blob/master/src/api/json/catalog.json#L520-L536

**Comment by austindrenski** [comment]
> It's already there 😄 https://github.com/SchemaStore/schemastore/blob/master/src/api/json/catalog.json#L520-L536

hot dog! chalk that one up to a bad regex 🤦🤦🤦

**Comment by toddbaert** [comment]
> > It's already there 😄 https://github.com/SchemaStore/schemastore/blob/master/src/api/json/catalog.json#L520-L536
> 
> hot dog! chalk that one up to a bad regex 🤦🤦🤦

NP Austin I'm glad had the idea too... you know what they say about "great minds".
