### ISSUE TITLE
[DOC] Define the expected behavior when a non-string value is returned when evaluating a targeting rule

### ISSUE THREAD

**Issue by beeme1mr** [open-feature/flagd#989]
### Change in the documentation

It's currently possible in flagd to define "shorthand" targeting rules that don't explicitly return a variant key. This is convenient because it reduces the size and overall complexity of boolean-based flag configurations. Consider the following configuration:

```json
{
  "flags": {
    "fibAlgo": {
      "variants": {
		"true": true,
        "false": false
      },
      "defaultVariant": "false",
      "state": "ENABLED",
      "targeting":  { "==" : [{ "var": "favoriteNumber" }, 1] }
    }
  }
}
```

Notice that the targeting rule doesn't return a variant key. However, if the `evaluation context` includes the `favoriteNumber` as 1, `true` will be returned. That's because flagd cases the boolean value to a string before looking in the variant map.

This behavior should be defined in the spec for in-process evaluators so that they all behave the same way.

**Comment by toddbaert** [comment]
In addition, we should add a test for this to the gherkin suite.

**Comment by beeme1mr** [comment]
The js in-process evaluator supports this behavior.

https://github.com/open-feature/js-sdk-contrib/pull/652

**Comment by toddbaert** [comment]
We have tests for this now, we just need to formally document it, I believe.

**Comment by beeme1mr** [comment]
https://flagd.dev/reference/flag-definitions/#boolean-variant-shorthand
